import ChenRanks.ArrangementHyperplaneResidues
import ChenRanks.ArrangementCurveField

/-!
# The original quadratic subspaces and their actual logarithmic images

Actual hyperplane residues prove degree-one injectivity. Consequently
every subspace of the original generator space is isomorphic to its
actual logarithmic image. Isotropy for the genuine quadratic realization
implies rational differential isotropy, and the paper's closed-form
construction applies to that same image without an independence or
closedness premise. The actual topological cup-product comparison remains
a separate theorem.
-/

noncomputable section

namespace ChenRanks.AffineArrangement

/-- The genuine base-change differential image of the constructed field
is the line generated by the original transcendental differential. -/
def curveFieldDifferentialLine (C F : Type*) [Field C] [Field F] [Algebra C F]
    {τ : Type*} (h a : F) (b : τ → F) : Prop :=
  LinearMap.range (KaehlerDifferential.mapBaseChange C (curveCoefficientField C h a b) F) =
    Submodule.span F {KaehlerDifferential.D C F h}

variable {d : ℕ} {ι : Type*} [Fintype ι] (A : AffineArrangement d ι)

/-- The actual image of a subspace of the original generator space. -/
def realizedLogarithmicSubspace (P : Submodule ℂ (ι → ℂ)) :
    Submodule ℂ Ω[RationalFunctionField (d := d)⁄ℂ] :=
  LinearMap.range (A.logarithmicRealization.comp P.subtype)

/-- The actual subspace is identified with its actual logarithmic image
using the proved original-hyperplane coefficient detection. -/
def logarithmicSubspaceEquiv (P : Submodule ℂ (ι → ℂ)) :
    P ≃ₗ[ℂ] A.realizedLogarithmicSubspace P :=
  LinearEquiv.ofInjective (A.logarithmicRealization.comp P.subtype)
    (A.logarithmicRealization_injective.comp P.subtype_injective)

theorem realizedLogarithmicSubspace_finrank (P : Submodule ℂ (ι → ℂ)) :
    Module.finrank ℂ (A.realizedLogarithmicSubspace P) = Module.finrank ℂ P :=
  (A.logarithmicSubspaceEquiv P).finrank_eq.symm

theorem realizedLogarithmicSubspace_le_logarithmicForms (P : Submodule ℂ (ι → ℂ)) :
    A.realizedLogarithmicSubspace P ≤ A.logarithmicForms := by
  rintro ω ⟨p, rfl⟩
  exact ⟨(p : ι → ℂ), rfl⟩

/-- Actual quadratic isotropy transports to the actual rational exterior
square via the genuine quadratic realization. -/
theorem realizedLogarithmicSubspace_isotropic (P : Submodule ℂ (ι → ℂ))
    (hP : ∀ p q : P, exteriorWedge (k := ℂ) (p : ι → ℂ) (q : ι → ℂ) ∈
      A.rationalQuadraticKernel) :
    ∀ p q : A.realizedLogarithmicSubspace P,
      exteriorWedge (k := RationalFunctionField (d := d))
        (p : Ω[RationalFunctionField (d := d)⁄ℂ])
        (q : Ω[RationalFunctionField (d := d)⁄ℂ]) = 0 := by
  intro p q
  obtain ⟨x, hx⟩ := p.property
  obtain ⟨y, hy⟩ := q.property
  rw [← hx, ← hy]
  exact (A.exteriorWedge_mem_rationalQuadraticKernel_iff x y).mp (hP x y)

/-- The actual subspace in the paper produces its actual finite curve
field and differential line. Degree-one independence and closedness are
conclusions of the arrangement construction, rather than inputs. -/
theorem quadratic_isotropic_subspace_admits_curve_differential_line
    (P : Submodule ℂ (ι → ℂ)) (hdim : 2 ≤ Module.finrank ℂ P)
    (hP : ∀ p q : P, exteriorWedge (k := ℂ) (p : ι → ℂ) (q : ι → ℂ) ∈
      A.rationalQuadraticKernel) :
    ∃ (h a : RationalFunctionField (d := d))
      (b : Fin (Module.finrank ℂ (A.realizedLogarithmicSubspace P)) →
        RationalFunctionField (d := d)),
      Transcendental ℂ h ∧
      FiniteDimensional (IntermediateField.adjoin ℂ {h}) (curveCoefficientField ℂ h a b) ∧
      (∀ p : P, ∃ η : Ω[(curveCoefficientField ℂ h a b)⁄ℂ],
        KaehlerDifferential.map ℂ ℂ (curveCoefficientField ℂ h a b)
          (RationalFunctionField (d := d)) η = A.logarithmicRealization p) ∧
      curveFieldDifferentialLine ℂ (RationalFunctionField (d := d)) h a b := by
  have hdim' : 2 ≤ Module.finrank ℂ (A.realizedLogarithmicSubspace P) := by
    rw [A.realizedLogarithmicSubspace_finrank]
    exact hdim
  obtain ⟨h, a, b, hh, hfinite, hpull, hline⟩ :=
    A.isotropic_logarithmicForms_admit_curve_differential_line
      (A.realizedLogarithmicSubspace P)
      (A.realizedLogarithmicSubspace_le_logarithmicForms P) hdim'
      (A.realizedLogarithmicSubspace_isotropic P hP)
  refine ⟨h, a, b, hh, hfinite, ?_, hline⟩
  intro p
  exact hpull (A.logarithmicSubspaceEquiv P p)

end ChenRanks.AffineArrangement
