import ChenRanks.ArrangementDifferentials
import ChenRanks.ClosedCurveField
import ChenRanks.CurveCoefficientDifferentials

/-!
# The curve-field construction for actual arrangement forms

The logarithmic subspace is the actual image of the polynomial-equation
realization. Its finite dimension and closedness are proved from the actual
finite arrangement. Applying the paper's closed-forms argument therefore
requires neither a finite-type function-field hypothesis nor a separate
closedness premise. The geometric projective curve model remains a later
step; the conclusion here is the actual finite intermediate field and the
original differential pullback image.
-/

noncomputable section

namespace ChenRanks.AffineArrangement

variable {d : ℕ} {ι : Type*} [Fintype ι] (A : AffineArrangement d ι)

/-- The actual space generated by the arrangement's logarithmic forms. -/
def logarithmicForms : Submodule ℂ Ω[RationalFunctionField (d := d)⁄ℂ] :=
  LinearMap.range A.logarithmicRealization

instance logarithmicForms_finiteDimensional : FiniteDimensional ℂ A.logarithmicForms :=
  LinearMap.finiteDimensional_range A.logarithmicRealization

/-- Every actual arrangement logarithmic form is closed. -/
theorem logarithmicForms_le_closed :
    A.logarithmicForms ≤ closedRationalForms ℂ (RationalFunctionField (d := d)) := by
  rintro ω ⟨c, rfl⟩
  exact A.logarithmicRealization_isClosed c

/-- The curve field in the paper is constructed from each actual isotropic
subspace of arrangement logarithmic forms. All structural field and
closedness inputs are discharged from the actual arrangement. -/
theorem isotropic_logarithmicForms_pull_back_from_curve_field
    (P : Submodule ℂ Ω[RationalFunctionField (d := d)⁄ℂ])
    (hP : P ≤ A.logarithmicForms)
    (hdim : 2 ≤ Module.finrank ℂ P)
    (hisotropic : ∀ p q : P,
      exteriorWedge (k := RationalFunctionField (d := d))
        (p : Ω[RationalFunctionField (d := d)⁄ℂ])
        (q : Ω[RationalFunctionField (d := d)⁄ℂ]) = 0) :
    ∃ (h a : RationalFunctionField (d := d))
      (b : Fin (Module.finrank ℂ P) → RationalFunctionField (d := d)),
      Transcendental ℂ h ∧ a ≠ 0 ∧
      FiniteDimensional (IntermediateField.adjoin ℂ {h})
        (curveCoefficientField ℂ h a b) ∧
      ∀ ω : P, ∃ η : Ω[(curveCoefficientField ℂ h a b)⁄ℂ],
        KaehlerDifferential.map ℂ ℂ (curveCoefficientField ℂ h a b)
          (RationalFunctionField (d := d)) η =
            (ω : Ω[RationalFunctionField (d := d)⁄ℂ]) := by
  letI : FiniteDimensional ℂ P :=
    FiniteDimensional.of_injective (Submodule.inclusion hP)
      (Submodule.inclusion_injective hP)
  exact closed_isotropic_forms_pull_back_from_curve_field ℂ P hdim
    (hP.trans A.logarithmicForms_le_closed) hisotropic

/-- For the same field constructed from the actual arrangement subspace,
the entire ambient base-change image is the line generated by `dh`. -/
theorem isotropic_logarithmicForms_admit_curve_differential_line
    (P : Submodule ℂ Ω[RationalFunctionField (d := d)⁄ℂ])
    (hP : P ≤ A.logarithmicForms)
    (hdim : 2 ≤ Module.finrank ℂ P)
    (hisotropic : ∀ p q : P,
      exteriorWedge (k := RationalFunctionField (d := d))
        (p : Ω[RationalFunctionField (d := d)⁄ℂ])
        (q : Ω[RationalFunctionField (d := d)⁄ℂ]) = 0) :
    ∃ (h a : RationalFunctionField (d := d))
      (b : Fin (Module.finrank ℂ P) → RationalFunctionField (d := d)),
      Transcendental ℂ h ∧
      FiniteDimensional (IntermediateField.adjoin ℂ {h})
        (curveCoefficientField ℂ h a b) ∧
      (∀ ω : P, ∃ η : Ω[(curveCoefficientField ℂ h a b)⁄ℂ],
        KaehlerDifferential.map ℂ ℂ (curveCoefficientField ℂ h a b)
          (RationalFunctionField (d := d)) η =
            (ω : Ω[RationalFunctionField (d := d)⁄ℂ])) ∧
      LinearMap.range (KaehlerDifferential.mapBaseChange ℂ
        (curveCoefficientField ℂ h a b) (RationalFunctionField (d := d))) =
          Submodule.span (RationalFunctionField (d := d))
            {KaehlerDifferential.D ℂ (RationalFunctionField (d := d)) h} := by
  obtain ⟨h, a, b, hh, _, hfinite, hpull⟩ :=
    A.isotropic_logarithmicForms_pull_back_from_curve_field P hP hdim hisotropic
  exact ⟨h, a, b, hh, hfinite, hpull,
    curveCoefficientField_baseChange_range_eq_span ℂ h a b hh hfinite⟩

end ChenRanks.AffineArrangement
