import Mathlib
import ChenRanks.ExteriorSeparation

/-!
# The actual differential line of a separable algebraic curve field

The rational-function field is the actual fraction field of `C[X]`.
Localization and separable extension give explicit linear equivalences
`Ω[RatFunc C⁄C] ≃ RatFunc C` and `Ω[L⁄C] ≃ L`.  In a further field
extension, the image of the actual Kähler base-change map is generated by
the differential of the image of `X`.  Its exterior products vanish.

No dimension or isotropy assumption is used.  The algebra structures and
their scalar towers describe a genuine field embedding.  The separable
extension hypothesis is a field-theoretic input; finite separable curve
fields satisfy it, but finiteness is not needed by these results.

Constructing that curve field from closed isotropic logarithmic forms, and
instantiating it for an actual arrangement, remain separate steps.
-/

noncomputable section

open scoped Polynomial TensorProduct
open Polynomial TensorProduct

namespace ChenRanks

variable (C : Type*) [Field C]

/-- Localization of the actual univariate polynomial differential module
gives a linear coordinate on the rational-function differential module. -/
def ratFuncDifferentialEquiv : Ω[RatFunc C⁄C] ≃ₗ[RatFunc C] RatFunc C := by
  letI : Algebra.FormallyEtale C[X] (RatFunc C) :=
    Algebra.FormallyEtale.of_isLocalization (nonZeroDivisors C[X])
  exact (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale
      C C[X] (RatFunc C)).symm ≪≫ₗ
    AlgebraTensorModule.congr (LinearEquiv.refl (RatFunc C) (RatFunc C))
      (KaehlerDifferential.polynomialEquiv C) ≪≫ₗ
    AlgebraTensorModule.rid C[X] (RatFunc C) (RatFunc C)

/-- The coordinate above sends the actual differential of `X` to one. -/
@[simp]
theorem ratFuncDifferentialEquiv_D_X :
    ratFuncDifferentialEquiv C
      (KaehlerDifferential.D C (RatFunc C) RatFunc.X) = 1 := by
  letI : Algebra.FormallyEtale C[X] (RatFunc C) :=
    Algebra.FormallyEtale.of_isLocalization (nonZeroDivisors C[X])
  change AlgebraTensorModule.rid C[X] (RatFunc C) (RatFunc C)
    (AlgebraTensorModule.congr (LinearEquiv.refl (RatFunc C) (RatFunc C))
      (KaehlerDifferential.polynomialEquiv C)
      ((KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale
        C C[X] (RatFunc C)).symm
          (KaehlerDifferential.D C (RatFunc C) RatFunc.X))) = 1
  rw [← RatFunc.algebraMap_X,
    KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale_symm_D_algebraMap]
  simp

section CurveField

variable (L : Type*) [Field L]
  [Algebra C L] [Algebra (RatFunc C) L] [IsScalarTower C (RatFunc C) L]
  [Algebra.IsSeparable (RatFunc C) L]

/-- Separable algebraic extension of a rational-function field preserves
the actual one-dimensional absolute differential module. -/
def curveDifferentialEquiv : Ω[L⁄C] ≃ₗ[L] L := by
  letI : Algebra.FormallyEtale (RatFunc C) L :=
    Algebra.FormallyEtale.of_isSeparable (RatFunc C) L
  exact (KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale
      C (RatFunc C) L).symm ≪≫ₗ
    AlgebraTensorModule.congr (LinearEquiv.refl L L)
      (ratFuncDifferentialEquiv C) ≪≫ₗ
    AlgebraTensorModule.rid (RatFunc C) L L

/-- The nonzero differential of the embedded transcendence generator. -/
def curveDifferentialGenerator : Ω[L⁄C] :=
  KaehlerDifferential.D C L (algebraMap (RatFunc C) L RatFunc.X)

@[simp]
theorem curveDifferentialEquiv_generator :
    curveDifferentialEquiv C L (curveDifferentialGenerator C L) = 1 := by
  letI : Algebra.FormallyEtale (RatFunc C) L :=
    Algebra.FormallyEtale.of_isSeparable (RatFunc C) L
  change AlgebraTensorModule.rid (RatFunc C) L L
    (AlgebraTensorModule.congr (LinearEquiv.refl L L)
      (ratFuncDifferentialEquiv C)
      ((KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale
        C (RatFunc C) L).symm
          (KaehlerDifferential.D C L
            (algebraMap (RatFunc C) L RatFunc.X)))) = 1
  rw [KaehlerDifferential.tensorKaehlerEquivOfFormallyEtale_symm_D_algebraMap]
  simp

theorem curveDifferentialGenerator_ne_zero : curveDifferentialGenerator C L ≠ 0 := by
  intro h
  have he := congrArg (curveDifferentialEquiv C L) h
  have hz : (1 : L) = 0 := by
    simpa only [curveDifferentialEquiv_generator, map_zero] using he
  exact one_ne_zero hz

/-- Every actual absolute one-form of the curve field is a multiple of `dh`. -/
theorem curve_differential_eq_smul (ω : Ω[L⁄C]) :
    ∃ a : L, a • curveDifferentialGenerator C L = ω := by
  refine ⟨curveDifferentialEquiv C L ω, ?_⟩
  apply (curveDifferentialEquiv C L).injective
  simp only [map_smul, curveDifferentialEquiv_generator, smul_eq_mul, mul_one]

/-- Cardinal dimension one, proved from the explicit coordinate rather
than asserted as a hypothesis. -/
theorem curve_differentials_rank_eq_one : Module.rank L Ω[L⁄C] = 1 :=
  rank_eq_one (curveDifferentialGenerator C L)
    (curveDifferentialGenerator_ne_zero C L) (curve_differential_eq_smul C L)

theorem curve_differentials_finrank_eq_one : Module.finrank L Ω[L⁄C] = 1 :=
  finrank_eq_one (curveDifferentialGenerator C L)
    (curveDifferentialGenerator_ne_zero C L) (curve_differential_eq_smul C L)

section AmbientField

variable (F : Type*) [Field F]
  [Algebra C F] [Algebra L F] [IsScalarTower C L F]

/-- The actual embedded base differential in the ambient function field. -/
def ambientCurveDifferential : Ω[F⁄C] :=
  KaehlerDifferential.D C F
    (algebraMap L F (algebraMap (RatFunc C) L RatFunc.X))

/-- Every tensor in the source of the actual base-change map maps to a
multiple of the embedded curve differential. -/
theorem curve_baseChange_eq_smul (t : F ⊗[L] Ω[L⁄C]) :
    ∃ a : F, a • ambientCurveDifferential C L F =
      KaehlerDifferential.mapBaseChange C L F t := by
  induction t with
  | zero => exact ⟨0, by simp⟩
  | add x y hx hy =>
    obtain ⟨a, ha⟩ := hx
    obtain ⟨b, hb⟩ := hy
    refine ⟨a + b, ?_⟩
    rw [add_smul, ha, hb, map_add]
  | tmul a ω =>
    obtain ⟨b, hb⟩ := curve_differential_eq_smul C L ω
    refine ⟨a * algebraMap L F b, ?_⟩
    rw [← hb, KaehlerDifferential.mapBaseChange_tmul, map_smul,
      curveDifferentialGenerator, KaehlerDifferential.map_D]
    change (a * algebraMap L F b) • ambientCurveDifferential C L F =
      a • (b • ambientCurveDifferential C L F)
    rw [← algebraMap_smul F b, smul_smul]

/-- The base-change image is exactly the span of the actual embedded `dh`. -/
theorem curve_baseChange_range_eq_span :
    LinearMap.range (KaehlerDifferential.mapBaseChange C L F) =
      Submodule.span F {ambientCurveDifferential C L F} := by
  apply le_antisymm
  · rintro _ ⟨t, rfl⟩
    obtain ⟨a, ha⟩ := curve_baseChange_eq_smul C L F t
    exact Submodule.mem_span_singleton.mpr ⟨a, ha⟩
  · apply Submodule.span_le.mpr
    intro ω hω
    rcases Set.mem_singleton_iff.mp hω with rfl
    refine ⟨1 ⊗ₜ[L] curveDifferentialGenerator C L, ?_⟩
    simp only [KaehlerDifferential.mapBaseChange_tmul, one_smul,
      curveDifferentialGenerator, ambientCurveDifferential, KaehlerDifferential.map_D]

/-- No finite-dimensionality is assumed for the ambient differential module. -/
theorem curve_baseChange_image_rank_le_one :
    Module.rank F (LinearMap.range (KaehlerDifferential.mapBaseChange C L F)) ≤ 1 := by
  have hg : ambientCurveDifferential C L F ∈
      LinearMap.range (KaehlerDifferential.mapBaseChange C L F) := by
    rw [curve_baseChange_range_eq_span C L F]
    exact Submodule.mem_span_singleton_self _
  apply rank_le_one
    (⟨ambientCurveDifferential C L F, hg⟩ :
      LinearMap.range (KaehlerDifferential.mapBaseChange C L F))
  intro ω
  obtain ⟨t, ht⟩ := ω.property
  obtain ⟨a, ha⟩ := curve_baseChange_eq_smul C L F t
  exact ⟨a, Subtype.ext (ha.trans ht)⟩

/-- Any two forms coming from the curve field have zero actual exterior
product over the ambient field. -/
theorem curve_baseChange_exteriorWedge_eq_zero (α β : Ω[F⁄C])
    (hα : α ∈ LinearMap.range (KaehlerDifferential.mapBaseChange C L F))
    (hβ : β ∈ LinearMap.range (KaehlerDifferential.mapBaseChange C L F)) :
    exteriorWedge (k := F) α β = 0 := by
  obtain ⟨x, hx⟩ := hα
  obtain ⟨y, hy⟩ := hβ
  obtain ⟨a, ha⟩ := curve_baseChange_eq_smul C L F x
  obtain ⟨b, hb⟩ := curve_baseChange_eq_smul C L F y
  rw [← hx, ← hy, ← ha, ← hb]
  apply Subtype.ext
  simp [exteriorWedge_coe]

/-- Isotropy of the actual base-change image follows from its construction,
rather than being an additional input to separation. -/
theorem curve_baseChange_image_isIsotropic :
    IsIsotropic (exteriorWedgeBilin (k := F))
      (LinearMap.range (KaehlerDifferential.mapBaseChange C L F)) := by
  intro α hα β hβ
  exact curve_baseChange_exteriorWedge_eq_zero C L F α β hα hβ

end AmbientField
end CurveField

end ChenRanks
