import ChenRanks.CurveDifferentialLine
import ChenRanks.DifferentialAlgebraicDependence

/-!
# Instantiating the differential line for the actual coefficient field

The rational-function algebra on `C(h,a,bᵢ)` is constructed from the genuine
equivalence `C(X) ≃ C(h)` and the genuine subfield inclusion.  A proved finite
extension of `C(h)` gives a finite, hence separable, extension of `C(X)`.
No rational-function algebra, scalar tower, separability, differential rank,
or isotropy is supplied as an additional hypothesis.
-/

noncomputable section

open scoped TensorProduct

namespace ChenRanks

variable (C : Type*) [Field C]
variable {F : Type*} [Field F] [Algebra C F] {ι : Type*}

/-- The actual rational-function embedding attached to `h`, with target
the original coefficient field, rather than a replacement field type. -/
def curveCoefficientRatFuncMap (h a : F) (b : ι → F)
    (hh : Transcendental C h) : RatFunc C →ₐ[C] curveCoefficientField C h a b := by
  let K := IntermediateField.adjoin C {h}
  let L := curveCoefficientField C h a b
  letI : IsScalarTower C K L := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  exact (IsScalarTower.toAlgHom C K L).comp
    (RatFunc.algEquivOfTranscendental h hh).toAlgHom

/-- The constructed map sends the genuine variable to the original `h`. -/
@[simp]
theorem curveCoefficientRatFuncMap_X (h a : F) (b : ι → F)
    (hh : Transcendental C h) :
    (curveCoefficientRatFuncMap C h a b hh RatFunc.X : F) = h := by
  change (RatFunc.algEquivOfTranscendental h hh RatFunc.X : F) = h
  exact RatFunc.algEquivOfTranscendental_X h hh

/-- Finiteness is transported along an actual field equivalence and the
actual finite inclusion; it is not assumed for the rational-function algebra. -/
theorem curveCoefficientRatFuncMap_finite (h a : F) (b : ι → F)
    (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b)) :
    (curveCoefficientRatFuncMap C h a b hh).toRingHom.Finite := by
  change ((algebraMap (IntermediateField.adjoin C {h})
    (curveCoefficientField C h a b)).comp
      (RatFunc.algEquivOfTranscendental h hh).toRingHom).Finite
  exact (RingHom.finite_algebraMap.mpr hfinite).comp
    (RatFunc.algEquivOfTranscendental h hh).toRingEquiv.finite

section CharacteristicZero

variable [CharZero C]

/-- The actual coefficient field has actual cardinal differential rank one. -/
theorem curveCoefficientField_differential_rank_eq_one
    (h a : F) (b : ι → F) (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b)) :
    Module.rank (curveCoefficientField C h a b)
      Ω[(curveCoefficientField C h a b)⁄C] = 1 := by
  let L := curveCoefficientField C h a b
  let f := curveCoefficientRatFuncMap C h a b hh
  letI : Algebra (RatFunc C) L := f.toRingHom.toAlgebra
  letI : IsScalarTower C (RatFunc C) L :=
    IsScalarTower.of_algebraMap_eq fun c ↦ (f.commutes c).symm
  letI : FiniteDimensional (RatFunc C) L :=
    curveCoefficientRatFuncMap_finite C h a b hh hfinite
  letI : Algebra.IsSeparable (RatFunc C) L := inferInstance
  exact curve_differentials_rank_eq_one C L

theorem curveCoefficientField_differential_finrank_eq_one
    (h a : F) (b : ι → F) (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b)) :
    Module.finrank (curveCoefficientField C h a b)
      Ω[(curveCoefficientField C h a b)⁄C] = 1 := by
  let L := curveCoefficientField C h a b
  let f := curveCoefficientRatFuncMap C h a b hh
  letI : Algebra (RatFunc C) L := f.toRingHom.toAlgebra
  letI : IsScalarTower C (RatFunc C) L :=
    IsScalarTower.of_algebraMap_eq fun c ↦ (f.commutes c).symm
  letI : FiniteDimensional (RatFunc C) L :=
    curveCoefficientRatFuncMap_finite C h a b hh hfinite
  letI : Algebra.IsSeparable (RatFunc C) L := inferInstance
  exact curve_differentials_finrank_eq_one C L

/-- The base-change image for this actual coefficient field is the line
generated by the actual differential of the original transcendental `h`. -/
theorem curveCoefficientField_baseChange_range_eq_span
    (h a : F) (b : ι → F) (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b)) :
    LinearMap.range (KaehlerDifferential.mapBaseChange C
      (curveCoefficientField C h a b) F) =
      Submodule.span F {KaehlerDifferential.D C F h} := by
  let L := curveCoefficientField C h a b
  let f := curveCoefficientRatFuncMap C h a b hh
  letI : Algebra (RatFunc C) L := f.toRingHom.toAlgebra
  letI : IsScalarTower C (RatFunc C) L :=
    IsScalarTower.of_algebraMap_eq fun c ↦ (f.commutes c).symm
  letI : FiniteDimensional (RatFunc C) L :=
    curveCoefficientRatFuncMap_finite C h a b hh hfinite
  letI : Algebra.IsSeparable (RatFunc C) L := inferInstance
  have hg : ambientCurveDifferential C L F = KaehlerDifferential.D C F h := by
    unfold ambientCurveDifferential
    change KaehlerDifferential.D C F
      (curveCoefficientRatFuncMap C h a b hh RatFunc.X : F) = _
    rw [curveCoefficientRatFuncMap_X]
  simpa only [hg] using curve_baseChange_range_eq_span C L F

/-- Isotropy follows for the actual base-change image, with every field
and scalar structure above constructed from the actual coefficient field. -/
theorem curveCoefficientField_baseChange_exteriorWedge_eq_zero
    (h a : F) (b : ι → F) (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b))
    (α β : Ω[F⁄C])
    (hα : α ∈ LinearMap.range (KaehlerDifferential.mapBaseChange C
      (curveCoefficientField C h a b) F))
    (hβ : β ∈ LinearMap.range (KaehlerDifferential.mapBaseChange C
      (curveCoefficientField C h a b) F)) :
    exteriorWedge (k := F) α β = 0 := by
  rw [curveCoefficientField_baseChange_range_eq_span C h a b hh hfinite] at hα hβ
  obtain ⟨x, hx⟩ := Submodule.mem_span_singleton.mp hα
  obtain ⟨y, hy⟩ := Submodule.mem_span_singleton.mp hβ
  rw [← hx, ← hy]
  apply Subtype.ext
  simp [exteriorWedge_coe]

/-- Forms in the original pullback image also have zero actual exterior
product.  The witnesses enter the base-change map with scalar factor one. -/
theorem curveCoefficientField_map_exteriorWedge_eq_zero
    (h a : F) (b : ι → F) (hh : Transcendental C h)
    (hfinite : FiniteDimensional (IntermediateField.adjoin C {h})
      (curveCoefficientField C h a b))
    (α β : Ω[F⁄C])
    (hα : α ∈ LinearMap.range (KaehlerDifferential.map C C
      (curveCoefficientField C h a b) F))
    (hβ : β ∈ LinearMap.range (KaehlerDifferential.map C C
      (curveCoefficientField C h a b) F)) :
    exteriorWedge (k := F) α β = 0 := by
  apply curveCoefficientField_baseChange_exteriorWedge_eq_zero C h a b hh hfinite α β
  · obtain ⟨ω, hω⟩ := hα
    refine ⟨(1 : F) ⊗ₜ[curveCoefficientField C h a b] ω, ?_⟩
    simpa only [KaehlerDifferential.mapBaseChange_tmul, one_smul] using hω
  · obtain ⟨ω, hω⟩ := hβ
    refine ⟨(1 : F) ⊗ₜ[curveCoefficientField C h a b] ω, ?_⟩
    simpa only [KaehlerDifferential.mapBaseChange_tmul, one_smul] using hω

end CharacteristicZero

end ChenRanks
