import ChenRanks.GroupAlgebraAugmentationSpan

/-! The actual first augmentation quotient has the universal property
for additive characters of the original group. It is the native quotient
of the actual augmentation kernel by its actual square, restricted to
the original base field. No rational dimension-subgroup theorem in higher
degrees, completed comparison, or formality is asserted.
-/

noncomputable section

namespace ChenRanks.GroupAlgebra

variable (k G : Type*) [Field k] [Group G]

def augmentationSquareWithin : Submodule k (augmentationLinearIdeal k G) :=
  ((augmentationIdeal k G) ^ 2).restrictScalars k |>.comap
    (augmentationLinearIdeal k G).subtype

abbrev augmentationCotangent :=
  augmentationLinearIdeal k G ⧸ augmentationSquareWithin k G

def augmentationDifferenceInIdeal (g : G) : augmentationLinearIdeal k G :=
  ⟨augmentationDifference k G g, augmentationDifference_mem k G g⟩

def augmentationCotangentClass (g : G) : augmentationCotangent k G :=
  (augmentationSquareWithin k G).mkQ (augmentationDifferenceInIdeal k G g)

/-- The original group law becomes genuine addition after quotienting
by the actual square of its augmentation ideal. -/
def augmentationCotangentCharacter : Additive G →+ augmentationCotangent k G where
  toFun g := augmentationCotangentClass k G g.toMul
  map_zero' := by
    apply (Submodule.Quotient.mk_eq_zero (augmentationSquareWithin k G)).mpr
    change augmentationDifference k G 1 ∈ (augmentationIdeal k G) ^ 2
    simp only [augmentationDifference, map_one, sub_self]
    exact Ideal.zero_mem _
  map_add' g h := by
    apply (Submodule.Quotient.eq (augmentationSquareWithin k G)).mpr
    change augmentationDifference k G (g.toMul * h.toMul) -
      (augmentationDifference k G g.toMul + augmentationDifference k G h.toMul) ∈
      (augmentationIdeal k G) ^ 2
    rw [augmentationDifference_mul, add_sub_cancel_left]
    rw [Submodule.pow_succ, Submodule.pow_one]
    exact Ideal.mul_mem_mul (augmentationDifference_mem k G g.toMul)
      (augmentationDifference_mem k G h.toMul)

variable (M : Type*) [AddCommGroup M] [Module k M]

def augmentationCharacterOnIdeal (χ : Additive G →+ M) :
    augmentationLinearIdeal k G →ₗ[k] M :=
  (characterLinear k G M χ).comp (augmentationLinearIdeal k G).subtype

theorem augmentationSquareWithin_le_character_ker (χ : Additive G →+ M) :
    augmentationSquareWithin k G ≤ LinearMap.ker (augmentationCharacterOnIdeal k G M χ) := by
  intro a ha
  change characterLinear k G M χ a.val = 0
  exact characterLinear_augmentation_square_zero k G M χ a.val ha

/-- True descent of an original character through the actual quotient. -/
def augmentationCotangentLift (χ : Additive G →+ M) :
    augmentationCotangent k G →ₗ[k] M :=
  (augmentationSquareWithin k G).liftQ (augmentationCharacterOnIdeal k G M χ)
    (augmentationSquareWithin_le_character_ker k G M χ)

@[simp]
theorem augmentationCotangentLift_class (χ : Additive G →+ M) (g : G) :
    augmentationCotangentLift k G M χ (augmentationCotangentClass k G g) =
      χ (Additive.ofMul g) :=
  characterLinear_difference k G M χ g

/-- The actual cotangent space is generated by the classes of original
group elements. This is derived from the actual augmentation span. -/
theorem augmentationCotangentClass_span :
    Submodule.span k (Set.range (augmentationCotangentClass k G)) = ⊤ := by
  apply top_unique
  intro z _
  obtain ⟨a, rfl⟩ := (augmentationSquareWithin k G).mkQ_surjective z
  have ha : a.val ∈ Submodule.span k (Set.range (augmentationDifference k G)) := by
    rw [← augmentationLinearIdeal_eq_span]
    exact a.property
  obtain ⟨c, hc⟩ := (Finsupp.mem_span_range_iff_exists_finsupp).mp ha
  have hsub : Finsupp.linearCombination k (augmentationDifferenceInIdeal k G) c = a := by
    apply Subtype.ext
    change (augmentationLinearIdeal k G).subtype
      (Finsupp.linearCombination k (augmentationDifferenceInIdeal k G) c) = a.val
    rw [Finsupp.apply_linearCombination]
    exact hc
  rw [← hsub, Finsupp.apply_linearCombination]
  rw [← Finsupp.range_linearCombination]
  exact LinearMap.mem_range.mpr ⟨c, rfl⟩

/-- Uniqueness on the original group classes, with no finite-generation
or dimensional hypothesis on the group. -/
theorem augmentationCotangentLift_unique (χ : Additive G →+ M)
    (f : augmentationCotangent k G →ₗ[k] M)
    (hf : ∀ g : G, f (augmentationCotangentClass k G g) = χ (Additive.ofMul g)) :
    f = augmentationCotangentLift k G M χ := by
  apply LinearMap.ext_on
    (augmentationCotangentClass_span k G)
  rintro _ ⟨g, rfl⟩
  exact (hf g).trans (augmentationCotangentLift_class k G M χ g).symm

end ChenRanks.GroupAlgebra
