import ChenRanks.KoszulObjects

/-!
# Actual homogeneous pieces of the symmetric-algebra Koszul module

The grading is transported from the genuine multivariate-polynomial algebra
along a genuine basis equivalence.  The homogeneous projections and finite
decomposition are proved, as are the degrees of the actual Koszul maps.
The degree `r` quotient uses coefficient degree `r+1` for cycles and degree
`r` for quadratic relations, matching the paper's convention.

No Hilbert dimension, Koszul exactness, stable decomposition, or Chen
comparison is assumed or asserted here.
-/

noncomputable section

open TensorProduct
open scoped BigOperators TensorProduct

namespace ChenRanks.Koszul

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [_root_.Module k V]
variable {ι : Type*} (b : _root_.Module.Basis ι k V)

/-- The actual degree-`n` subspace of the original symmetric algebra. -/
def homogeneousS (n : ℕ) : Submodule k (S k V) :=
  (MvPolynomial.homogeneousSubmodule ι k n).comap
    (SymmetricAlgebra.equivMvPolynomial b).toLinearMap

@[simp] theorem mem_homogeneousS (n : ℕ) (s : S k V) :
    s ∈ homogeneousS k V b n ↔
      MvPolynomial.IsHomogeneous (SymmetricAlgebra.equivMvPolynomial b s) n := Iff.rfl

theorem homogeneousS_mul {m n : ℕ} {s t : S k V}
    (hs : s ∈ homogeneousS k V b m) (ht : t ∈ homogeneousS k V b n) :
    s * t ∈ homogeneousS k V b (m + n) := by
  change MvPolynomial.IsHomogeneous (SymmetricAlgebra.equivMvPolynomial b (s * t)) _
  rw [map_mul]
  exact ((mem_homogeneousS k V b m s).mp hs).mul
    ((mem_homogeneousS k V b n t).mp ht)

theorem homogeneousS_one : (1 : S k V) ∈ homogeneousS k V b 0 := by
  change MvPolynomial.IsHomogeneous (SymmetricAlgebra.equivMvPolynomial b 1) 0
  rw [map_one]
  exact MvPolynomial.isHomogeneous_one ι k

theorem homogeneousS_ι_basis (i : ι) :
    SymmetricAlgebra.ι k V (b i) ∈ homogeneousS k V b 1 := by
  change MvPolynomial.IsHomogeneous
    (SymmetricAlgebra.equivMvPolynomial b (SymmetricAlgebra.ι k V (b i))) 1
  rw [SymmetricAlgebra.equivMvPolynomial_ι_apply]
  exact MvPolynomial.isHomogeneous_X k i

/-- Every actual generator has degree one, proved from its basis expansion. -/
theorem homogeneousS_ι [Fintype ι] (v : V) :
    SymmetricAlgebra.ι k V v ∈ homogeneousS k V b 1 := by
  classical
  rw [← b.sum_repr v, map_sum]
  exact (homogeneousS k V b 1).sum_mem fun i _ ↦ by
    rw [map_smul]
    exact (homogeneousS k V b 1).smul_mem (b.repr v i) (homogeneousS_ι_basis k V b i)

/-- The actual homogeneous projection on the original symmetric algebra. -/
def homogeneousProjection (n : ℕ) : S k V →ₗ[k] S k V :=
  (SymmetricAlgebra.equivMvPolynomial b).symm.toLinearMap ∘ₗ
    MvPolynomial.homogeneousComponent n ∘ₗ
      (SymmetricAlgebra.equivMvPolynomial b).toLinearMap

@[simp] theorem polynomial_homogeneousProjection (n : ℕ) (s : S k V) :
    SymmetricAlgebra.equivMvPolynomial b (homogeneousProjection k V b n s) =
      MvPolynomial.homogeneousComponent n (SymmetricAlgebra.equivMvPolynomial b s) := by
  simp [homogeneousProjection]

theorem homogeneousProjection_mem (n : ℕ) (s : S k V) :
    homogeneousProjection k V b n s ∈ homogeneousS k V b n := by
  rw [mem_homogeneousS, polynomial_homogeneousProjection]
  exact MvPolynomial.homogeneousComponent_isHomogeneous n _

theorem homogeneousProjection_of_mem {m n : ℕ} {s : S k V}
    (hs : s ∈ homogeneousS k V b n) :
    homogeneousProjection k V b m s = if m = n then s else 0 := by
  apply (SymmetricAlgebra.equivMvPolynomial b).injective
  have hs' : SymmetricAlgebra.equivMvPolynomial b s ∈
      MvPolynomial.homogeneousSubmodule ι k n := hs
  rw [polynomial_homogeneousProjection,
    MvPolynomial.homogeneousComponent_of_mem hs']
  split_ifs <;> simp

/-- Each actual polynomial is a finite sum of its actual homogeneous pieces. -/
theorem sum_homogeneousProjection (s : S k V) :
    (∑ n ∈ Finset.range ((SymmetricAlgebra.equivMvPolynomial b s).totalDegree + 1),
      homogeneousProjection k V b n s) = s := by
  apply (SymmetricAlgebra.equivMvPolynomial b).injective
  simp only [map_sum, polynomial_homogeneousProjection]
  exact MvPolynomial.sum_homogeneousComponent _

section TensorPieces

variable (W : Type*) [AddCommGroup W] [_root_.Module k W]

/-- The actual coefficient-degree subspace of `S ⊗ W`, generated by
actual pure tensors whose polynomial coefficient is homogeneous. -/
def tensorHomogeneous (n : ℕ) : Submodule k (S k V ⊗[k] W) :=
  Submodule.span k {t | ∃ s : S k V, s ∈ homogeneousS k V b n ∧
    ∃ w : W, t = s ⊗ₜ[k] w}

theorem tmul_mem_tensorHomogeneous (n : ℕ) (s : S k V)
    (hs : s ∈ homogeneousS k V b n) (w : W) :
    s ⊗ₜ[k] w ∈ tensorHomogeneous k V b W n :=
  Submodule.subset_span ⟨s, hs, w, rfl⟩

private def tensorScalarLinear (s : S k V) :
    (S k V ⊗[k] W) →ₗ[k] (S k V ⊗[k] W) where
  toFun t := s • t
  map_add' x y := smul_add s x y
  map_smul' c x := smul_comm s c x

/-- Multiplying by a genuine degree-`m` coefficient adds `m` to the
coefficient degree of an arbitrary homogeneous tensor. -/
theorem smul_mem_tensorHomogeneous {m n : ℕ} (s : S k V)
    (hs : s ∈ homogeneousS k V b m) (t : S k V ⊗[k] W)
    (ht : t ∈ tensorHomogeneous k V b W n) :
    s • t ∈ tensorHomogeneous k V b W (m + n) := by
  have hle : tensorHomogeneous k V b W n ≤
      (tensorHomogeneous k V b W (m + n)).comap (tensorScalarLinear k V W s) := by
    apply Submodule.span_le.mpr
    rintro x ⟨f, hf, w, rfl⟩
    change s • (f ⊗ₜ[k] w) ∈ tensorHomogeneous k V b W (m + n)
    simpa only [TensorProduct.smul_tmul', smul_eq_mul] using
      tmul_mem_tensorHomogeneous k V b W (m + n) (s * f)
        (homogeneousS_mul k V b hs hf) w
  exact hle ht

end TensorPieces

abbrev c1Degree (n : ℕ) := tensorHomogeneous k V b V n
abbrev c2Degree (n : ℕ) := tensorHomogeneous k V b (⋀[k]^2 V) n

/-- The actual multiplication differential raises coefficient degree by one. -/
theorem delta1_preserves_degree [Fintype ι] (n : ℕ) :
    c1Degree k V b n ≤ (homogeneousS k V b (n + 1)).comap
      ((delta1 k V).restrictScalars k) := by
  apply Submodule.span_le.mpr
  rintro x ⟨s, hs, v, rfl⟩
  change delta1 k V (s ⊗ₜ[k] v) ∈ homogeneousS k V b (n + 1)
  rw [delta1_tmul]
  exact homogeneousS_mul k V b hs (homogeneousS_ι k V b v)

/-- The genuine exterior-square differential has coefficient degree one. -/
theorem delta2Linear_degree_one [Fintype ι] (w : ⋀[k]^2 V) :
    delta2Linear k V w ∈ c1Degree k V b 1 := by
  have hle : Submodule.span k (Set.range (exteriorPower.ιMulti k 2)) ≤
      (c1Degree k V b 1).comap (delta2Linear k V) := by
    apply Submodule.span_le.mpr
    rintro x ⟨a, rfl⟩
    change delta2Linear k V (exteriorPower.ιMulti k 2 a) ∈ c1Degree k V b 1
    rw [delta2Linear_wedge]
    have hx := tmul_mem_tensorHomogeneous k V b V 1
      (SymmetricAlgebra.ι k V (a 0)) (homogeneousS_ι k V b (a 0)) (a 1)
    have hy := tmul_mem_tensorHomogeneous k V b V 1
      (SymmetricAlgebra.ι k V (a 1)) (homogeneousS_ι k V b (a 1)) (a 0)
    simpa only [TensorProduct.smul_tmul', smul_eq_mul, mul_one] using
      (c1Degree k V b 1).sub_mem hx hy
  apply hle
  rw [exteriorPower.ιMulti_span k 2 V]
  exact Submodule.mem_top

/-- The actual second Koszul differential raises coefficient degree by one. -/
theorem delta2_preserves_degree [Fintype ι] (n : ℕ) :
    c2Degree k V b n ≤ (c1Degree k V b (n + 1)).comap
      ((delta2 k V).restrictScalars k) := by
  apply Submodule.span_le.mpr
  rintro x ⟨s, hs, w, rfl⟩
  change delta2 k V (s ⊗ₜ[k] w) ∈ c1Degree k V b (n + 1)
  rw [delta2_tmul]
  exact smul_mem_tensorHomogeneous k V b V s hs (delta2Linear k V w)
    (delta2Linear_degree_one k V b w)

/-- The actual degree-`r` cycles, with the paper's coefficient shift. -/
def cycleDegree (r : ℕ) : Submodule k (C1 k V) :=
  c1Degree k V b (r + 1) ⊓ (LinearMap.ker (delta1 k V)).restrictScalars k

variable (K : Submodule k (⋀[k]^2 V))

private def relationDegreeAmbient (r : ℕ) :
    (homogeneousS k V b r ⊗[k] K) →ₗ[k] C1 k V :=
  (delta2 k V).restrictScalars k ∘ₗ
    TensorProduct.map (homogeneousS k V b r).subtype K.subtype

private theorem relationDegreeAmbient_mem_cycles [Fintype ι] (r : ℕ)
    (x : homogeneousS k V b r ⊗[k] K) :
    relationDegreeAmbient k V b K r x ∈ cycleDegree k V b r := by
  constructor
  · apply delta2_preserves_degree k V b r
    induction x with
    | zero => simp
    | add x y hx hy => simpa only [map_add] using (c2Degree k V b r).add_mem hx hy
    | tmul s w =>
      simpa only [TensorProduct.map_tmul, Submodule.subtype_apply] using
        tmul_mem_tensorHomogeneous k V b (⋀[k]^2 V) r s s.property (w : ⋀[k]^2 V)
  · apply LinearMap.mem_ker.mpr
    have h := DFunLike.congr_fun (delta1_comp_delta2 k V)
      (TensorProduct.map (homogeneousS k V b r).subtype K.subtype x)
    simpa only [relationDegreeAmbient, LinearMap.comp_apply, LinearMap.zero_apply,
      LinearMap.restrictScalars_apply] using h

/-- The genuine homogeneous relation map, with cycles as its actual codomain. -/
def relationDegree [Fintype ι] (r : ℕ) :
    (homogeneousS k V b r ⊗[k] K) →ₗ[k] cycleDegree k V b r :=
  (relationDegreeAmbient k V b K r).codRestrict (cycleDegree k V b r)
    (relationDegreeAmbient_mem_cycles k V b K r)

/-- The genuine homogeneous Koszul quotient in the paper's degree convention. -/
abbrev homogeneousModule [Fintype ι] (r : ℕ) :=
  cycleDegree k V b r ⧸ LinearMap.range (relationDegree k V b K r)

end ChenRanks.Koszul
