import ChenRanks.KoszulLocalizedGenerators
import ChenRanks.KoszulLocalizedSeparation

/-!
# Actual separation annihilates the whole literal point-localized module

The actual transverse coordinate kills each true pivot class by actual
separation. Those classes generate the whole literal scalar extension
by the proved original second-term surjection and true Koszul relation.
Consequently the actual localized ideal of transverse linear coordinates
is contained in the native annihilator of the entire literal module.

Neither annihilation, generation, freedom, component-map isomorphism,
annihilator radicality, nor effective decomposition is an input.
-/

noncomputable section

namespace ChenRanks.Koszul

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [_root_.Module k V]
variable (K : Submodule k (⋀[k]^2 V))
variable (R : Type*) [CommRing R] [Algebra (S k V) R]
variable [FiniteDimensional k V] [CharZero k]

/-- Scalar vanishing on all true pivot classes gives vanishing on the
entire literal scalar extension. The pivot-generation assertion is
already proved from the actual Koszul complex, and is not a premise. -/
theorem coefficientExtendedScalar_kills_of_pivotClasses (v : V)
    (hv : IsUnit (extendedCoefficient k V R v)) (r : R)
    (hpivot : ∀ w, r • coefficientExtendedExteriorClass k V K R (exteriorWedge v w) = 0)
    (z : CoefficientExtendedModule k V K R) : r • z = 0 := by
  have hspan : extendedPivotSpan k V K R v ≤
      LinearMap.ker (LinearMap.lsmul R (CoefficientExtendedModule k V K R) r) := by
    apply Submodule.span_le.mpr
    rintro t ⟨w, rfl⟩
    exact hpivot w
  rw [extendedPivotSpan_eq_top k V K R v hv] at hspan
  exact hspan (show z ∈ (⊤ : Submodule R (CoefficientExtendedModule k V K R)) from trivial)

variable (E : Type*) [AddCommGroup E] [_root_.Module k E] [FiniteDimensional k E]
variable (P : Submodule k E) (I : Submodule k (⋀[k]^2 E))

omit [AddCommGroup V] [_root_.Module k V] [FiniteDimensional k V] [CommRing R]
    [Algebra (S k V) R] in
/-- True separation annihilates the whole literal localized original
Koszul module by every actual transverse coordinate. -/
theorem actualPointLocalized_transverseCoordinate_annihilates
    (hsep : I ⊓ mixedExterior P ≤ pureExterior P)
    (e : E) (heP : e ∈ P) (v : _root_.Module.Dual k E) (hv : v e = 1)
    (u : P.dualAnnihilator)
    (z : CoefficientExtendedModule k (_root_.Module.Dual k E) (exteriorAnnihilator k E 2 I)
      (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))) :
    extendedCoefficient k (_root_.Module.Dual k E)
      (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))
        (u : _root_.Module.Dual k E) • z = 0 := by
  letI : _root_.Module.Free k P.dualAnnihilator :=
    _root_.Module.Free.of_basis (_root_.Module.Basis.ofVectorSpace k P.dualAnnihilator)
  let c := _root_.Module.finBasis k P.dualAnnihilator
  exact coefficientExtendedScalar_kills_of_pivotClasses k (_root_.Module.Dual k E)
    (exteriorAnnihilator k E 2 I)
    (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e)) v
    (pointLocalCoefficient_isUnit k (_root_.Module.Dual k E) (pointOfVector k E e) hv)
    (extendedCoefficient k (_root_.Module.Dual k E)
      (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e)) u)
    (fun w ↦ actualPointLocalized_transverseCoordinate_kills_pivotClass k E P I c hsep e heP v hv w u) z

omit [AddCommGroup V] [_root_.Module k V] [FiniteDimensional k V] [CommRing R]
    [Algebra (S k V) R] in
/-- The transverse coordinate belongs to the native annihilator of the
entire literal point localization, rather than only to a generator test. -/
theorem actualPointLocalized_transverseCoordinate_mem_annihilator
    (hsep : I ⊓ mixedExterior P ≤ pureExterior P)
    (e : E) (heP : e ∈ P) (v : _root_.Module.Dual k E) (hv : v e = 1)
    (u : P.dualAnnihilator) :
    extendedCoefficient k (_root_.Module.Dual k E)
      (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))
        (u : _root_.Module.Dual k E) ∈
      _root_.Module.annihilator
        (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))
        (CoefficientExtendedModule k (_root_.Module.Dual k E) (exteriorAnnihilator k E 2 I)
          (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))) := by
  exact _root_.Module.mem_annihilator.mpr
    (actualPointLocalized_transverseCoordinate_annihilates k E P I hsep e heP v hv u)

omit [CharZero k] [AddCommGroup V] [_root_.Module k V] [FiniteDimensional k V]
    [CommRing R] [Algebra (S k V) R] [FiniteDimensional k E] in
/-- The actual ideal generated by the original transverse linear forms. -/
def transverseCoefficientIdeal : Ideal (S k (_root_.Module.Dual k E)) :=
  Ideal.span ((SymmetricAlgebra.ι k (_root_.Module.Dual k E)) ''
    (P.dualAnnihilator : Set (_root_.Module.Dual k E)))

omit [AddCommGroup V] [_root_.Module k V] [FiniteDimensional k V] [CommRing R]
    [Algebra (S k V) R] in
/-- The image of the actual transverse-coordinate ideal under the true
localization map annihilates the whole literal localized original module. -/
theorem actualPointLocalized_transverseIdeal_le_annihilator
    (hsep : I ⊓ mixedExterior P ≤ pureExterior P)
    (e : E) (heP : e ∈ P) (v : _root_.Module.Dual k E) (hv : v e = 1) :
    (transverseCoefficientIdeal k E P).map
      (algebraMap (S k (_root_.Module.Dual k E))
        (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))) ≤
      _root_.Module.annihilator
        (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))
        (CoefficientExtendedModule k (_root_.Module.Dual k E) (exteriorAnnihilator k E 2 I)
          (PointLocalCoefficientRing k (_root_.Module.Dual k E) (pointOfVector k E e))) := by
  apply Ideal.map_le_iff_le_comap.mpr
  apply Ideal.span_le.mpr
  rintro s ⟨u, hu, rfl⟩
  exact actualPointLocalized_transverseCoordinate_mem_annihilator k E P I hsep e heP v hv ⟨u, hu⟩

end ChenRanks.Koszul
