import ChenRanks.KoszulMetabelianLieModel
import Mathlib.Algebra.Lie.Nilpotent
import Mathlib.RingTheory.Ideal.Operations

/-!
# The actual lower central filtration of the actual Koszul Lie model

The augmentation is mathlib's genuine `SymmetricAlgebra.algebraMapInv`.
Its kernel is proved equal to the ideal generated by the original vector
generators. Polynomial actions preserve actual invariant elements of
any native Lie ideal. Actual second-tensor generation then proves that
the entire original Koszul coordinate is the native first derived ideal.
The native lower central series is subsequently computed by genuine
powers of the actual augmentation ideal.

This is a filtration identity. Identification of successive quotients
with homogeneous pieces, and comparison with the original group's
lower-central quotients, are separate theorems and are not defined here.
-/

noncomputable section

open TensorProduct
open scoped TensorProduct

namespace ChenRanks.Koszul

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [_root_.Module k V]
variable (K : Submodule k (⋀[k]^2 V))

local instance originalModuleBase : _root_.Module k (Module k V K) :=
  Submodule.Quotient.module' (S := k) (LinearMap.range (relationMap k V K))

local instance originalModuleBaseSMulZero : SMulZeroClass k (Module k V K) :=
  Submodule.Quotient.smulZeroClass' (S := k) (LinearMap.range (relationMap k V K))

/-- The genuine augmentation sends every original vector generator to zero. -/
def actualSymmetricAugmentation : S k V →ₐ[k] k :=
  SymmetricAlgebra.algebraMapInv (R := k) (M := V)

@[simp]
theorem actualSymmetricAugmentation_ι (u : V) :
    actualSymmetricAugmentation k V (SymmetricAlgebra.ι k V u) = 0 := by
  simp only [actualSymmetricAugmentation, SymmetricAlgebra.algebraMapInv,
    SymmetricAlgebra.lift_ι_apply, LinearMap.zero_apply]

@[simp]
theorem actualSymmetricAugmentation_algebraMap (c : k) :
    actualSymmetricAugmentation k V (algebraMap k (S k V) c) = c :=
  SymmetricAlgebra.algebraMap_leftInverse (R := k) V c

/-- The actual kernel ideal of the actual symmetric augmentation. -/
def actualAugmentationIdeal : Ideal (S k V) :=
  RingHom.ker (actualSymmetricAugmentation k V).toRingHom

theorem actualAugmentationIdeal_ι_mem (u : V) :
    SymmetricAlgebra.ι k V u ∈ actualAugmentationIdeal k V := by
  change actualSymmetricAugmentation k V (SymmetricAlgebra.ι k V u) = 0
  exact actualSymmetricAugmentation_ι k V u

/-- Removing the actual scalar constant leaves an element generated by
the actual vector generators. -/
theorem sub_augmentation_mem_generatorIdeal (s : S k V) :
    s - algebraMap k (S k V) (actualSymmetricAugmentation k V s) ∈
      Ideal.span (Set.range (SymmetricAlgebra.ι k V)) := by
  induction s using SymmetricAlgebra.induction with
  | algebraMap c =>
    rw [actualSymmetricAugmentation_algebraMap, sub_self]
    exact Ideal.zero_mem _
  | ι u =>
    rw [actualSymmetricAugmentation_ι, map_zero, sub_zero]
    exact Ideal.subset_span ⟨u, rfl⟩
  | mul s t hs ht =>
    rw [map_mul]
    have he : s * t - algebraMap k (S k V)
        (actualSymmetricAugmentation k V s * actualSymmetricAugmentation k V t) =
        s * (t - algebraMap k (S k V) (actualSymmetricAugmentation k V t)) +
          (s - algebraMap k (S k V) (actualSymmetricAugmentation k V s)) *
            algebraMap k (S k V) (actualSymmetricAugmentation k V t) := by
      rw [map_mul]
      ring
    rw [he]
    apply Ideal.add_mem
    · exact (Ideal.span (Set.range (SymmetricAlgebra.ι k V))).smul_mem s ht
    · simpa only [smul_eq_mul, mul_comm] using
        (Ideal.span (Set.range (SymmetricAlgebra.ι k V))).smul_mem
          (algebraMap k (S k V) (actualSymmetricAugmentation k V t)) hs
  | add s t hs ht =>
    rw [map_add, map_add]
    have he : s + t -
        (algebraMap k (S k V) (actualSymmetricAugmentation k V s) +
          algebraMap k (S k V) (actualSymmetricAugmentation k V t)) =
        (s - algebraMap k (S k V) (actualSymmetricAugmentation k V s)) +
          (t - algebraMap k (S k V) (actualSymmetricAugmentation k V t)) := by abel
    rw [he]
    exact Ideal.add_mem _ hs ht

/-- The genuine augmentation kernel is proved generated by the original
vector generators, without a grading or finite-generation premise. -/
theorem actualAugmentationIdeal_eq_span :
    actualAugmentationIdeal k V = Ideal.span (Set.range (SymmetricAlgebra.ι k V)) := by
  apply le_antisymm
  · intro s hs
    have hzero : actualSymmetricAugmentation k V s = 0 := hs
    simpa only [hzero, map_zero, sub_zero] using
      sub_augmentation_mem_generatorIdeal k V s
  · apply Ideal.span_le.mpr
    rintro _ ⟨u, rfl⟩
    exact actualAugmentationIdeal_ι_mem k V u

/-- Polynomial coefficients preserve invariant elements of every actual
native Lie ideal, by genuine symmetric-algebra induction and adjoint action. -/
theorem invariantPolynomialSmul_mem
    (I : LieIdeal k (MetabelianLieModel k V K)) (s : S k V) (m : Module k V K)
    (hm : MetabelianLieModel.invariantInclusion k V K m ∈ I) :
    MetabelianLieModel.invariantInclusion k V K (s • m) ∈ I := by
  induction s using SymmetricAlgebra.induction generalizing m with
  | algebraMap c =>
    rw [algebraMap_smul, map_smul]
    exact I.smul_mem c hm
  | ι u =>
    rw [← MetabelianLieModel.generator_invariant_bracket]
    exact I.lie_mem hm
  | mul s t hs ht =>
    rw [mul_smul]
    exact hs (t • m) (ht m hm)
  | add s t hs ht =>
    rw [add_smul, map_add]
    exact I.add_mem (hs m hm) (ht m hm)

/-- An actual polynomial submodule of the invariant coordinate yields an
actual Lie ideal with the real Koszul bracket. -/
def invariantPolynomialIdeal (N : Submodule (S k V) (Module k V K)) :
    LieIdeal k (MetabelianLieModel k V K) where
  carrier := {x | x.generator = 0 ∧ x.invariant ∈ N}
  zero_mem' := ⟨rfl, N.zero_mem⟩
  add_mem' {x y} hx hy := by
    change (x + y).generator = 0 ∧ (x + y).invariant ∈ N
    exact ⟨by rw [MetabelianLieModel.generator_add, hx.1, hy.1, add_zero],
      N.add_mem hx.2 hy.2⟩
  smul_mem' c x hx := by
    refine ⟨?_, ?_⟩
    · rw [MetabelianLieModel.generator_smul, hx.1, smul_zero]
    · change c • x.invariant ∈ N
      simpa only [algebraMap_smul] using
        N.smul_mem (algebraMap k (S k V) c) hx.2
  lie_mem := by
    intro x y hy
    refine ⟨rfl, ?_⟩
    simp only [MetabelianLieModel.invariant_bracket, hy.1, map_zero,
      zero_smul, zero_add, sub_zero]
    exact N.smul_mem (SymmetricAlgebra.ι k V x.generator) hy.2

@[simp]
theorem mem_invariantPolynomialIdeal (N : Submodule (S k V) (Module k V K))
    (x : MetabelianLieModel k V K) :
    x ∈ invariantPolynomialIdeal k V K N ↔ x.generator = 0 ∧ x.invariant ∈ N := Iff.rfl

@[simp]
theorem invariantInclusion_mem_invariantPolynomialIdeal
    (N : Submodule (S k V) (Module k V K)) (m : Module k V K) :
    MetabelianLieModel.invariantInclusion k V K m ∈ invariantPolynomialIdeal k V K N ↔
      m ∈ N := by
  simp only [mem_invariantPolynomialIdeal,
    MetabelianLieModel.invariantInclusion_generator,
    MetabelianLieModel.invariantInclusion_invariant, true_and]

theorem eq_invariantInclusion_of_generator_eq_zero (x : MetabelianLieModel k V K)
    (hx : x.generator = 0) :
    x = MetabelianLieModel.invariantInclusion k V K x.invariant := by
  apply MetabelianLieModel.ext
  · exact hx
  · rfl

/-- The native commutator operation on invariant ideals is exactly
multiplication by the actual augmentation ideal. -/
theorem lie_top_invariantPolynomialIdeal
    (N : Submodule (S k V) (Module k V K)) :
    ⁅(⊤ : LieIdeal k (MetabelianLieModel k V K)), invariantPolynomialIdeal k V K N⁆ =
      invariantPolynomialIdeal k V K (actualAugmentationIdeal k V • N) := by
  apply le_antisymm
  · rw [LieSubmodule.lie_le_iff]
    intro x _hx y hy
    refine ⟨rfl, ?_⟩
    simp only [MetabelianLieModel.invariant_bracket, hy.1, map_zero,
      zero_smul, zero_add, sub_zero]
    exact Submodule.smul_mem_smul (actualAugmentationIdeal_ι_mem k V x.generator) hy.2
  · intro x hx
    have hmem : MetabelianLieModel.invariantInclusion k V K x.invariant ∈
        ⁅(⊤ : LieIdeal k (MetabelianLieModel k V K)), invariantPolynomialIdeal k V K N⁆ := by
      refine Submodule.smul_induction_on hx.2 ?_ ?_
      · intro s hs m hm
        rw [actualAugmentationIdeal_eq_span] at hs
        refine Submodule.span_induction
          (p := fun s _ => MetabelianLieModel.invariantInclusion k V K (s • m) ∈
            ⁅(⊤ : LieIdeal k (MetabelianLieModel k V K)),
              invariantPolynomialIdeal k V K N⁆) ?_ ?_ ?_ ?_ hs
        · rintro _ ⟨u, rfl⟩
          rw [← MetabelianLieModel.generator_invariant_bracket]
          exact LieSubmodule.lie_mem_lie
            (show MetabelianLieModel.generatorInclusion k V K u ∈
              (⊤ : LieIdeal k (MetabelianLieModel k V K)) from trivial)
            ((invariantInclusion_mem_invariantPolynomialIdeal k V K N m).mpr hm)
        · change MetabelianLieModel.invariantInclusion k V K ((0 : S k V) • m) ∈
            ⁅(⊤ : LieIdeal k (MetabelianLieModel k V K)),
              invariantPolynomialIdeal k V K N⁆
          rw [zero_smul, map_zero]
          exact LieSubmodule.zero_mem _
        · intro s t _hs _ht ihs iht
          rw [add_smul, map_add]
          exact add_mem ihs iht
        · intro a s _hs ih
          rw [smul_eq_mul, mul_smul]
          exact invariantPolynomialSmul_mem k V K _ a (s • m) ih
      · intro m n hm hn
        rw [map_add]
        exact add_mem hm hn
    rw [eq_invariantInclusion_of_generator_eq_zero k V K x hx.1]
    exact hmem

/-- Actual powers of the actual augmentation ideal on the original module. -/
def augmentationPowerModule (r : ℕ) : Submodule (S k V) (Module k V K) :=
  actualAugmentationIdeal k V ^ r • (⊤ : Submodule (S k V) (Module k V K))

def augmentationPowerInvariantIdeal (r : ℕ) : LieIdeal k (MetabelianLieModel k V K) :=
  invariantPolynomialIdeal k V K (augmentationPowerModule k V K r)

theorem augmentationPowerModule_succ (r : ℕ) :
    augmentationPowerModule k V K (r + 1) =
      actualAugmentationIdeal k V • augmentationPowerModule k V K r := by
  unfold augmentationPowerModule
  rw [pow_succ', Submodule.mul_smul]

theorem augmentationPowerInvariantIdeal_zero :
    augmentationPowerInvariantIdeal k V K 0 = MetabelianLieModel.invariantIdeal k V K := by
  ext x
  simp only [augmentationPowerInvariantIdeal, augmentationPowerModule,
    pow_zero, Ideal.one_eq_top, Submodule.top_smul, mem_invariantPolynomialIdeal,
    Submodule.mem_top, and_true, MetabelianLieModel.mem_invariantIdeal]

variable [FiniteDimensional k V] [CharZero k]

omit [FiniteDimensional k V] [CharZero k] in
/-- Actual constant second-tensor classes belong to the native derived ideal. -/
theorem constantWedgeClass_invariant_mem_derived (w : ⋀[k]^2 V) :
    MetabelianLieModel.invariantInclusion k V K (constantWedgeClass k V K w) ∈
      LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1 := by
  have hle : Submodule.span k (Set.range (exteriorPower.ιMulti k 2)) ≤
      (LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1).toSubmodule.comap
        (MetabelianLieModel.generatorBracketMap k V K) := by
    apply Submodule.span_le.mpr
    rintro _ ⟨a, rfl⟩
    change MetabelianLieModel.generatorBracketMap k V K (exteriorPower.ιMulti k 2 a) ∈
      LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1
    have ha : exteriorPower.ιMulti k 2 a = exteriorWedge (a 0) (a 1) := by
      change exteriorPower.ιMulti k 2 a = exteriorPower.ιMulti k 2 ![a 0, a 1]
      congr 1
      funext i
      fin_cases i <;> rfl
    rw [ha, MetabelianLieModel.generatorBracketMap_exteriorWedge]
    exact LieSubmodule.lie_mem_lie
      (show MetabelianLieModel.generatorInclusion k V K (a 0) ∈
        (⊤ : LieIdeal k (MetabelianLieModel k V K)) from trivial)
      (show MetabelianLieModel.generatorInclusion k V K (a 1) ∈
        (⊤ : LieIdeal k (MetabelianLieModel k V K)) from trivial)
  apply hle
  rw [exteriorPower.ιMulti_span k 2 V]
  exact Submodule.mem_top

/-- Actual second-tensor surjectivity proves that the whole original
invariant coordinate is the native derived ideal. -/
theorem invariantInclusion_mem_derived (m : Module k V K) :
    MetabelianLieModel.invariantInclusion k V K m ∈
      LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1 := by
  obtain ⟨z, rfl⟩ := secondTensorToModule_surjective k V K m
  induction z using TensorProduct.induction_on with
  | zero =>
    rw [map_zero, map_zero]
    exact LieSubmodule.zero_mem _
  | tmul s w =>
    have he : secondTensorToModule k V K (s ⊗ₜ[k] w) = s • constantWedgeClass k V K w := by
      rw [constantWedgeClass_apply, ← map_smul]
      simp only [TensorProduct.smul_tmul', smul_eq_mul, mul_one]
    rw [he]
    exact invariantPolynomialSmul_mem k V K _ s _
      (constantWedgeClass_invariant_mem_derived k V K w)
  | add x y hx hy =>
    rw [map_add, map_add]
    exact add_mem hx hy

/-- This is equality of native Lie ideals, proved from original generation. -/
theorem model_derived_one_eq_invariantIdeal :
    LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1 =
      MetabelianLieModel.invariantIdeal k V K := by
  apply le_antisymm (MetabelianLieModel.derived_one_le_invariantIdeal k V K)
  intro x hx
  rw [eq_invariantInclusion_of_generator_eq_zero k V K x hx]
  exact invariantInclusion_mem_derived k V K x.invariant

/-- Mathlib indexes the native lower central series from zero. Its `(r+1)`
term is ordinary Γ_(r+2), and is proved equal to actual m^r W. -/
theorem model_lowerCentralSeries_eq_augmentationPower (r : ℕ) :
    LieModule.lowerCentralSeries k (MetabelianLieModel k V K)
      (MetabelianLieModel k V K) (r + 1) = augmentationPowerInvariantIdeal k V K r := by
  induction r with
  | zero =>
    change LieAlgebra.derivedSeries k (MetabelianLieModel k V K) 1 =
      augmentationPowerInvariantIdeal k V K 0
    rw [model_derived_one_eq_invariantIdeal, augmentationPowerInvariantIdeal_zero]
  | succ r ih =>
    rw [LieModule.lowerCentralSeries_succ, ih]
    change ⁅(⊤ : LieIdeal k (MetabelianLieModel k V K)),
      invariantPolynomialIdeal k V K (augmentationPowerModule k V K r)⁆ = _
    rw [lie_top_invariantPolynomialIdeal]
    unfold augmentationPowerInvariantIdeal
    rw [augmentationPowerModule_succ]

end ChenRanks.Koszul
