import ChenRanks.KoszulPointThirdContraction

/-!
# The genuine pointwise contraction cokernel away from the origin

Both quotients below use actual exterior powers and actual contraction
maps. Their equivalence follows from the explicit nonzero-point Koszul
homotopy. This is a pointwise algebraic statement; the identification of
either quotient with the original module's tensor fibre is a separate
theorem and is not assumed here.
-/

noncomputable section

namespace ChenRanks.Koszul

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [_root_.Module k V]
variable (K : Submodule k (⋀[k]^2 V)) (a : V →ₗ[k] k)

/-- The actual second contraction, with target restricted to the actual
kernel of the point functional by the proved contraction identity. -/
def pointTwoToKernel : (⋀[k]^2 V) →ₗ[k] LinearMap.ker a :=
  (pointDeltaTwo k V a).codRestrict (LinearMap.ker a) (fun w ↦
    DFunLike.congr_fun (pointEvaluation_comp_pointDeltaTwo k V a) w)

/-- The actual contraction of the given quadratic subspace. -/
def pointQuadraticRelation : K →ₗ[k] LinearMap.ker a :=
  (pointTwoToKernel k V a).comp K.subtype

/-- The genuine third contraction and actual quadratic inclusion together
define the pointwise second-term relations. -/
def pointThirdQuadraticRelations : ((⋀[k]^3 V) × K) →ₗ[k] (⋀[k]^2 V) :=
  (pointDeltaThree k V a).coprod K.subtype

/-- The canonical map from the actual second exterior term to the actual
first contraction-kernel quotient. -/
def pointSecondToQuotient : (⋀[k]^2 V) →ₗ[k]
    (LinearMap.ker a ⧸ LinearMap.range (pointQuadraticRelation k V K a)) :=
  (LinearMap.range (pointQuadraticRelation k V K a)).mkQ.comp (pointTwoToKernel k V a)

@[simp] theorem pointSecondToQuotient_quadratic (w : K) :
    pointSecondToQuotient k V K a (w : ⋀[k]^2 V) = 0 := by
  change (Submodule.Quotient.mk (pointQuadraticRelation k V K a w) :
    LinearMap.ker a ⧸ LinearMap.range (pointQuadraticRelation k V K a)) = 0
  exact (Submodule.Quotient.mk_eq_zero _).mpr (LinearMap.mem_range_self _ _)

@[simp] theorem pointSecondToQuotient_third (w : ⋀[k]^3 V) :
    pointSecondToQuotient k V K a (pointDeltaThree k V a w) = 0 := by
  have hw : pointTwoToKernel k V a (pointDeltaThree k V a w) = 0 := by
    apply Subtype.ext
    exact DFunLike.congr_fun (pointDeltaTwo_comp_pointDeltaThree k V a) w
  change (LinearMap.range (pointQuadraticRelation k V K a)).mkQ
    (pointTwoToKernel k V a (pointDeltaThree k V a w)) = 0
  rw [hw, map_zero]

theorem pointTwoToKernel_surjective (ha : a ≠ 0) :
    Function.Surjective (pointTwoToKernel k V a) := by
  intro w
  have hw : (w : V) ∈ LinearMap.range (pointDeltaTwo k V a) := by
    rw [pointDeltaTwo_range_eq_ker k V a ha]
    exact w.property
  obtain ⟨z, hz⟩ := hw
  exact ⟨z, Subtype.ext hz⟩

theorem pointSecondToQuotient_surjective (ha : a ≠ 0) :
    Function.Surjective (pointSecondToQuotient k V K a) :=
  (Submodule.mkQ_surjective (LinearMap.range (pointQuadraticRelation k V K a))).comp
    (pointTwoToKernel_surjective k V a ha)

/-- The actual pointwise kernel is generated by the actual third
contraction image and the actual quadratic inclusion. -/
theorem pointSecondToQuotient_ker (ha : a ≠ 0) :
    LinearMap.ker (pointSecondToQuotient k V K a) =
      LinearMap.range (pointThirdQuadraticRelations k V K a) := by
  ext z
  constructor
  · intro hz
    have hzero : (Submodule.Quotient.mk (pointTwoToKernel k V a z) :
        LinearMap.ker a ⧸ LinearMap.range (pointQuadraticRelation k V K a)) = 0 := hz
    obtain ⟨x, hx⟩ := (Submodule.Quotient.mk_eq_zero
      (LinearMap.range (pointQuadraticRelation k V K a))).mp hzero
    have hxval := congrArg Subtype.val hx
    change pointDeltaTwo k V a (x : ⋀[k]^2 V) = pointDeltaTwo k V a z at hxval
    have hcycle : z - (x : ⋀[k]^2 V) ∈ LinearMap.ker (pointDeltaTwo k V a) := by
      apply LinearMap.mem_ker.mpr
      rw [map_sub, ← hxval, sub_self]
    rw [← pointDeltaThree_range_eq_ker k V a ha] at hcycle
    obtain ⟨y, hy⟩ := hcycle
    exact ⟨(y, x), by
      change pointDeltaThree k V a y + (x : ⋀[k]^2 V) = z
      rw [hy, sub_add_cancel]⟩
  · rintro ⟨⟨y, x⟩, rfl⟩
    apply LinearMap.mem_ker.mpr
    change pointSecondToQuotient k V K a
      (pointDeltaThree k V a y + (x : ⋀[k]^2 V)) = 0
    rw [map_add, pointSecondToQuotient_third, pointSecondToQuotient_quadratic, add_zero]

/-- A proved equivalence of actual contraction quotients away from the
origin; no tensor fibre or Aomoto identification is asserted by definition. -/
def pointContractionCokerEquiv (ha : a ≠ 0) :
    ((⋀[k]^2 V) ⧸ LinearMap.range (pointThirdQuadraticRelations k V K a)) ≃ₗ[k]
      (LinearMap.ker a ⧸ LinearMap.range (pointQuadraticRelation k V K a)) :=
  (Submodule.quotEquivOfEq _ _ (pointSecondToQuotient_ker k V K a ha).symm).trans
    ((pointSecondToQuotient k V K a).quotKerEquivOfSurjective
      (pointSecondToQuotient_surjective k V K a ha))

end ChenRanks.Koszul
