import Mathlib

/-!
# The actual first two Koszul differentials and their quotient

For a module `V` over a commutative ring `k`, this file uses the actual
symmetric algebra `S = SymmetricAlgebra k V` and exterior square `⋀[k]^2 V`.
It constructs the first two Koszul differentials from their formulas, proves
that their composite is zero, and defines the actual quotient by the image
of a supplied quadratic-relation submodule `K ⊆ ⋀[k]^2 V`.

`K` is input quadratic data.  No differential, exactness hypothesis, dimension
formula, resonance decomposition, or Chen comparison is an input hypothesis.

The construction is presently ungraded.  No assertion about homogeneous
pieces, Hilbert functions, effective regularity, or the arrangement Chen-rank
conjecture is made here.
-/

noncomputable section

open TensorProduct
open scoped TensorProduct

namespace ChenRanks.Koszul

variable (k : Type*) [CommRing k]
variable (V : Type*) [AddCommGroup V] [Module k V]

/-- The actual symmetric algebra generated by `V`. -/
abbrev S := SymmetricAlgebra k V

/-- The actual first tensor module in the Koszul complex, with polynomial
coefficients placed first in the tensor product. -/
abbrev C1 := S k V ⊗[k] V

/-- The actual second tensor module in the Koszul complex. -/
abbrev C2 := S k V ⊗[k] (⋀[k]^2 V)

/-- The multiplication differential `δ₁(s ⊗ v) = s · ι(v)`. -/
def delta1 : C1 k V →ₗ[S k V] S k V :=
  AlgebraTensorModule.lift
    (LinearMap.toSpanSingleton (S k V) (V →ₗ[k] S k V) (SymmetricAlgebra.ι k V))

@[simp] theorem delta1_tmul (s : S k V) (v : V) :
    delta1 k V (s ⊗ₜ[k] v) = s * SymmetricAlgebra.ι k V v :=
  rfl

/-- The alternating formula for the second differential on two vectors. -/
def delta2Alternating : V [⋀^Fin 2]→ₗ[k] C1 k V where
  toFun a :=
    (SymmetricAlgebra.ι k V (a 0)) • ((1 : S k V) ⊗ₜ[k] a 1) -
      (SymmetricAlgebra.ι k V (a 1)) • ((1 : S k V) ⊗ₜ[k] a 0)
  map_update_add' a i x y := by
    fin_cases i <;>
      simp [Function.update, map_add, add_smul, TensorProduct.tmul_add] <;> abel
  map_update_smul' a i c x := by
    fin_cases i
    · simp [Function.update, TensorProduct.tmul_smul, smul_sub, smul_assoc]
      rw [smul_comm (SymmetricAlgebra.ι k V (a 1)) c]
    · simp [Function.update, TensorProduct.tmul_smul, smul_sub, smul_assoc]
      rw [smul_comm (SymmetricAlgebra.ι k V (a 0)) c]
  map_eq_zero_of_eq' a i j h hij := by
    fin_cases i <;> fin_cases j
    · exact (hij rfl).elim
    · change a 0 = a 1 at h
      change
        (SymmetricAlgebra.ι k V (a 0)) • ((1 : S k V) ⊗ₜ[k] a 1) -
          (SymmetricAlgebra.ι k V (a 1)) • ((1 : S k V) ⊗ₜ[k] a 0) = 0
      simp only [h, sub_self]
    · change a 1 = a 0 at h
      change
        (SymmetricAlgebra.ι k V (a 0)) • ((1 : S k V) ⊗ₜ[k] a 1) -
          (SymmetricAlgebra.ι k V (a 1)) • ((1 : S k V) ⊗ₜ[k] a 0) = 0
      simp only [h, sub_self]
    · exact (hij rfl).elim

/-- Descent of the actual alternating formula to the exterior square. -/
def delta2Linear : (⋀[k]^2 V) →ₗ[k] C1 k V :=
  exteriorPower.alternatingMapLinearEquiv (delta2Alternating k V)

@[simp] theorem delta2Linear_wedge (a : Fin 2 → V) :
    delta2Linear k V (exteriorPower.ιMulti k 2 a) =
      (SymmetricAlgebra.ι k V (a 0)) • ((1 : S k V) ⊗ₜ[k] a 1) -
        (SymmetricAlgebra.ι k V (a 1)) • ((1 : S k V) ⊗ₜ[k] a 0) := by
  simp [delta2Linear, delta2Alternating]

/-- Extension of the second differential to polynomial coefficients. -/
def delta2 : C2 k V →ₗ[S k V] C1 k V :=
  AlgebraTensorModule.lift
    (LinearMap.toSpanSingleton (S k V) ((⋀[k]^2 V) →ₗ[k] C1 k V)
      (delta2Linear k V))

@[simp] theorem delta2_tmul (s : S k V) (w : ⋀[k]^2 V) :
    delta2 k V (s ⊗ₜ[k] w) = s • delta2Linear k V w :=
  rfl

/-- The two-vector formula is a cycle because the symmetric algebra is
commutative. -/
theorem delta1_delta2Linear :
    (delta1 k V).restrictScalars k ∘ₗ delta2Linear k V = 0 := by
  apply exteriorPower.linearMap_ext
  ext a
  simp only [LinearMap.compAlternatingMap_apply, LinearMap.comp_apply,
    LinearMap.restrictScalars_apply, delta2Linear_wedge, map_sub, map_smul,
    delta1_tmul, one_mul, smul_eq_mul, LinearMap.zero_apply, sub_eq_zero]
  exact mul_comm (SymmetricAlgebra.ι k V (a 0)) (SymmetricAlgebra.ι k V (a 1))

/-- The actual first two Koszul differentials compose to zero. -/
theorem delta1_comp_delta2 :
    delta1 k V ∘ₗ delta2 k V = 0 := by
  apply AlgebraTensorModule.ext
  intro s w
  simp only [LinearMap.comp_apply, delta2_tmul, map_smul]
  have hw := DFunLike.congr_fun (delta1_delta2Linear k V) w
  simpa using congrArg (fun t : S k V ↦ s • t) hw

variable (K : Submodule k (⋀[k]^2 V))

/-- The second differential restricted to the actual submodule of quadratic
relations, without any hypothesis on that submodule. -/
def delta2K : (S k V ⊗[k] K) →ₗ[S k V] C1 k V :=
  (delta2 k V).comp (AlgebraTensorModule.lTensor (S k V) (S k V) K.subtype)

/-- Its image lies in the actual kernel of multiplication. -/
theorem delta2K_mem_cycles (x : S k V ⊗[k] K) :
    delta2K k V K x ∈ LinearMap.ker (delta1 k V) := by
  apply LinearMap.mem_ker.mpr
  have h := DFunLike.congr_fun (delta1_comp_delta2 k V)
    (AlgebraTensorModule.lTensor (S k V) (S k V) K.subtype x)
  simpa [delta2K] using h

/-- The relation map with codomain restricted to cycles; its existence follows
from the proved differential identity. -/
def relationMap : (S k V ⊗[k] K) →ₗ[S k V] LinearMap.ker (delta1 k V) :=
  (delta2K k V K).codRestrict (LinearMap.ker (delta1 k V))
    (delta2K_mem_cycles k V K)

/-- The Koszul module `ker δ₁ / im δ₂|K`. -/
abbrev Module :=
  LinearMap.ker (delta1 k V) ⧸ LinearMap.range (relationMap k V K)

end ChenRanks.Koszul
