import Mathlib
import ChenRanks.LogarithmicResidues
import ChenRanks.DVRNormalizedDifferential
import ChenRanks.DifferentialAlgebraicDependence

/-!
# An actual logarithmic two-form lattice and its actual residue

The source is an actual A-submodule of the second exterior power over F
of the actual field Kähler module.  It is generated by actual regular
wedges and by the actual uniformizer logarithmic form wedged with actual
regular forms.

The residue is constructed by the actual normalized contraction,
multiplication by the actual uniformizer, the inverse of the proved
injective actual regular differential map onto its actual range, and
the actual map to residue-field differentials.  The residue identities
are proved from this construction, not taken as assumptions.

The intermediate DVR result retains actual formal smoothness of A/C.
Polynomial-chart localizations derive this in the preceding module.
No assertion is made that all geometric or exceptional-divisor models
have already been connected to those structural hypotheses.
-/

noncomputable section

open TensorProduct
open scoped TensorProduct

namespace ChenRanks

section ActualExteriorScalarRestriction

variable (C A F : Type*) [CommRing C] [CommRing A] [Field F]
  [Algebra C F] [Algebra A F]

/-- Preserve the native field module before introducing scalar restriction. -/
abbrev exteriorTwoFormNativeFieldModule : Module F (⋀[F]^2 Ω[F⁄C]) :=
  Submodule.module _

local instance : Module F (⋀[F]^2 Ω[F⁄C]) := exteriorTwoFormNativeFieldModule C F

local instance : SMul F (⋀[F]^2 Ω[F⁄C]) :=
  (exteriorTwoFormNativeFieldModule C F).toSMul

/-- The canonical restriction of the actual exterior-square module
along the actual algebra map, supplied explicitly because mathlib does
not install this scalar restriction as a general instance. -/
instance (priority := 100) exteriorTwoFormModuleRestriction : Module A (⋀[F]^2 Ω[F⁄C]) :=
  Module.compHom (⋀[F]^2 Ω[F⁄C]) (algebraMap A F)

/-- Cache precisely the scalar action of the preceding canonical module;
this does not introduce a different scalar dictionary. -/
instance (priority := 100) exteriorTwoFormSMulRestriction : SMul A (⋀[F]^2 Ω[F⁄C]) :=
  (exteriorTwoFormModuleRestriction C A F).toSMul

local instance : Module A (⋀[F]^2 Ω[F⁄C]) := exteriorTwoFormModuleRestriction C A F

local instance : SMul A (⋀[F]^2 Ω[F⁄C]) :=
  (exteriorTwoFormModuleRestriction C A F).toSMul

instance exteriorTwoFormScalarTower : IsScalarTower A F (⋀[F]^2 Ω[F⁄C]) where
  smul_assoc a f w := by
    rw [Algebra.smul_def]
    change (algebraMap A F a * f) • w = (algebraMap A F a) • (f • w)
    exact mul_smul _ _ _

instance exteriorTwoFormScalarComm : SMulCommClass A F (⋀[F]^2 Ω[F⁄C]) where
  smul_comm a f w := by
    change (algebraMap A F a) • (f • w) = f • ((algebraMap A F a) • w)
    simp only [smul_smul, mul_comm]

instance exteriorTwoFormScalarCommRev : SMulCommClass F A (⋀[F]^2 Ω[F⁄C]) :=
  SMulCommClass.symm A F (⋀[F]^2 Ω[F⁄C])

end ActualExteriorScalarRestriction

section ActualLogarithmicTwoForms

variable (C A F : Type*) [Field C] [CharZero C] [CommRing A] [IsDomain A] [Field F]
  [Algebra C A] [Algebra C F] [Algebra A F] [IsScalarTower C A F]
  [IsFractionRing A F] [IsDiscreteValuationRing A] [Algebra.EssFiniteType C A]
  [Algebra.FormallySmooth C A]

local instance : Module F (⋀[F]^2 Ω[F⁄C]) := exteriorTwoFormNativeFieldModule C F

local instance : SMul F (⋀[F]^2 Ω[F⁄C]) :=
  (exteriorTwoFormNativeFieldModule C F).toSMul

local instance : Module A (⋀[F]^2 Ω[F⁄C]) := exteriorTwoFormModuleRestriction C A F

local instance : SMul A (⋀[F]^2 Ω[F⁄C]) :=
  (exteriorTwoFormModuleRestriction C A F).toSMul

local instance : IsScalarTower A F (⋀[F]^2 Ω[F⁄C]) := exteriorTwoFormScalarTower C A F

/-- Actual regular wedges, considered as an A-bilinear map into the actual
second exterior power over F. -/
def regularTwoFormBilinear : Ω[A⁄C] →ₗ[A] Ω[A⁄C] →ₗ[A] ⋀[F]^2 Ω[F⁄C] :=
  LinearMap.mk₂ A
    (fun ω η ↦ exteriorWedge (k := F) (E := Ω[F⁄C])
      (KaehlerDifferential.map C C A F ω) (KaehlerDifferential.map C C A F η))
    (by
      intro ω₁ ω₂ η
      dsimp only
      rw [map_add]
      exact ((exteriorWedgeBilin (k := F) (E := Ω[F⁄C])).flip
        (KaehlerDifferential.map C C A F η)).map_add _ _)
    (by
      intro a ω η
      dsimp only
      rw [map_smul, ← algebraMap_smul F a (KaehlerDifferential.map C C A F ω)]
      change ((exteriorWedgeBilin (k := F) (E := Ω[F⁄C])).flip
        (KaehlerDifferential.map C C A F η))
        (algebraMap A F a • KaehlerDifferential.map C C A F ω) =
        algebraMap A F a • ((exteriorWedgeBilin (k := F) (E := Ω[F⁄C])).flip
          (KaehlerDifferential.map C C A F η)) (KaehlerDifferential.map C C A F ω)
      exact ((exteriorWedgeBilin (k := F) (E := Ω[F⁄C])).flip
        (KaehlerDifferential.map C C A F η)).map_smul
          (algebraMap A F a) (KaehlerDifferential.map C C A F ω))
    (by
      intro ω η₁ η₂
      dsimp only
      rw [map_add]
      exact (exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
        (KaehlerDifferential.map C C A F ω)).map_add _ _)
    (by
      intro a ω η
      dsimp only
      rw [map_smul, ← algebraMap_smul F a (KaehlerDifferential.map C C A F η)]
      change exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
        (KaehlerDifferential.map C C A F ω)
        (algebraMap A F a • KaehlerDifferential.map C C A F η) =
        algebraMap A F a • exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
          (KaehlerDifferential.map C C A F ω) (KaehlerDifferential.map C C A F η)
      exact (exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
        (KaehlerDifferential.map C C A F ω)).map_smul
          (algebraMap A F a) (KaehlerDifferential.map C C A F η))

/-- The actual tensor presentation of regular two-forms. -/
def regularTwoFormMap : Ω[A⁄C] ⊗[A] Ω[A⁄C] →ₗ[A] ⋀[F]^2 Ω[F⁄C] :=
  TensorProduct.lift (regularTwoFormBilinear C A F)

omit [CharZero C] [IsDomain A] [IsFractionRing A F] [IsDiscreteValuationRing A]
  [Algebra.EssFiniteType C A] [Algebra.FormallySmooth C A] in
@[simp]
theorem regularTwoFormMap_tmul (ω η : Ω[A⁄C]) :
    regularTwoFormMap C A F (ω ⊗ₜ[A] η) =
      exteriorWedge (k := F) (KaehlerDifferential.map C C A F ω)
        (KaehlerDifferential.map C C A F η) := rfl

/-- The actual uniformizer logarithmic form wedged with an actual regular
form, as an A-linear map. -/
def logarithmicMixedTwoFormMap (π : A) (hπ : Irreducible π) :
    Ω[A⁄C] →ₗ[A] ⋀[F]^2 Ω[F⁄C] where
  toFun η := exteriorWedge (k := F) (E := Ω[F⁄C])
    (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))
    (KaehlerDifferential.map C C A F η)
  map_add' η₁ η₂ := by
    rw [map_add]
    exact (exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
      (logarithmicDifferential C F
        (LogResidueCore.fractionUniformizerUnit A F π hπ))).map_add _ _
  map_smul' a η := by
    rw [map_smul, ← algebraMap_smul F a (KaehlerDifferential.map C C A F η)]
    change exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
      (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))
      (algebraMap A F a • KaehlerDifferential.map C C A F η) =
      algebraMap A F a • exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
        (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))
        (KaehlerDifferential.map C C A F η)
    exact (exteriorWedgeBilin (k := F) (E := Ω[F⁄C])
      (logarithmicDifferential C F
        (LogResidueCore.fractionUniformizerUnit A F π hπ))).map_smul
          (algebraMap A F a) (KaehlerDifferential.map C C A F η)

omit [CharZero C] [IsDomain A] [IsDiscreteValuationRing A]
  [Algebra.EssFiniteType C A] [Algebra.FormallySmooth C A] in
@[simp]
theorem logarithmicMixedTwoFormMap_apply (π : A) (hπ : Irreducible π) (η : Ω[A⁄C]) :
    logarithmicMixedTwoFormMap C A F π hπ η =
      exteriorWedge (k := F)
        (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))
        (KaehlerDifferential.map C C A F η) := rfl

/-- The actual logarithmic A-lattice in the actual F-exterior square.
It is defined by actual form images, without any residue condition. -/
def logarithmicTwoFormLattice (π : A) (hπ : Irreducible π) :
    Submodule A (⋀[F]^2 Ω[F⁄C]) :=
  LinearMap.range (regularTwoFormMap C A F) ⊔
    LinearMap.range (logarithmicMixedTwoFormMap C A F π hπ)

omit [CharZero C] [IsDomain A] [IsDiscreteValuationRing A]
  [Algebra.EssFiniteType C A] [Algebra.FormallySmooth C A] in
theorem regularTwoFormMap_mem_lattice (π : A) (hπ : Irreducible π)
    (u : Ω[A⁄C] ⊗[A] Ω[A⁄C]) :
    regularTwoFormMap C A F u ∈ logarithmicTwoFormLattice C A F π hπ :=
  Submodule.mem_sup_left ⟨u, rfl⟩

omit [CharZero C] [IsDomain A] [IsDiscreteValuationRing A]
  [Algebra.EssFiniteType C A] [Algebra.FormallySmooth C A] in
theorem logarithmicMixedTwoFormMap_mem_lattice (π : A) (hπ : Irreducible π)
    (η : Ω[A⁄C]) :
    logarithmicMixedTwoFormMap C A F π hπ η ∈ logarithmicTwoFormLattice C A F π hπ :=
  Submodule.mem_sup_right ⟨η, rfl⟩

/-- Actual normalized contraction followed by actual uniformizer multiplication. -/
def uniformizerScaledContraction (π : A) (hπ : Irreducible π) :
    (⋀[F]^2 Ω[F⁄C]) →ₗ[A] Ω[F⁄C] :=
  let d := dependenceContraction (k := F) (E := Ω[F⁄C])
    (uniformizerFractionDifferentialDual C A F π hπ)
  π • { toFun := d
        map_add' := d.map_add
        map_smul' := by
          intro a w
          change d (algebraMap A F a • w) = a • d w
          rw [map_smul]
          exact algebraMap_smul F a (d w) }

/-- Actual regular preimages for contracted regular wedges. -/
def regularTwoFormPreimageBilinear (π : A) (hπ : Irreducible π) :
    Ω[A⁄C] →ₗ[A] Ω[A⁄C] →ₗ[A] Ω[A⁄C] :=
  let b := (LinearMap.lsmul A Ω[A⁄C]).compl₁₂
    (uniformizerLocalDifferentialDual C A π hπ) (LinearMap.id : Ω[A⁄C] →ₗ[A] Ω[A⁄C])
  π • (b - b.flip)

/-- Actual tensor-linear preimages of the uniformizer-scaled contraction. -/
def regularTwoFormPreimage (π : A) (hπ : Irreducible π) :
    Ω[A⁄C] ⊗[A] Ω[A⁄C] →ₗ[A] Ω[A⁄C] :=
  TensorProduct.lift (regularTwoFormPreimageBilinear C A π hπ)

@[simp]
theorem regularTwoFormPreimage_tmul (π : A) (hπ : Irreducible π) (ω η : Ω[A⁄C]) :
    regularTwoFormPreimage C A π hπ (ω ⊗ₜ[A] η) =
      π • (uniformizerLocalDifferentialDual C A π hπ ω • η -
        uniformizerLocalDifferentialDual C A π hπ η • ω) := rfl

/-- Actual regular preimages for contracted logarithmic mixed forms. -/
def logarithmicMixedTwoFormPreimage (π : A) (hπ : Irreducible π) :
    Ω[A⁄C] →ₗ[A] Ω[A⁄C] :=
  LinearMap.id -
    (LinearMap.toSpanSingleton A Ω[A⁄C] (KaehlerDifferential.D C A π)).comp
      (uniformizerLocalDifferentialDual C A π hπ)

@[simp]
theorem logarithmicMixedTwoFormPreimage_apply (π : A) (hπ : Irreducible π) (η : Ω[A⁄C]) :
    logarithmicMixedTwoFormPreimage C A π hπ η =
      η - uniformizerLocalDifferentialDual C A π hπ η • KaehlerDifferential.D C A π := rfl

/-- The contraction of a genuine regular wedge has a genuine regular
preimage divisible by the uniformizer. -/
theorem uniformizerScaledContraction_regularWedge (π : A) (hπ : Irreducible π)
    (ω η : Ω[A⁄C]) :
    uniformizerScaledContraction C A F π hπ
      (exteriorWedge (k := F) (KaehlerDifferential.map C C A F ω)
        (KaehlerDifferential.map C C A F η)) =
      KaehlerDifferential.map C C A F
        (π • (uniformizerLocalDifferentialDual C A π hπ ω • η -
          uniformizerLocalDifferentialDual C A π hπ η • ω)) := by
  change π • dependenceContraction (k := F) (E := Ω[F⁄C])
    (uniformizerFractionDifferentialDual C A F π hπ)
    (exteriorWedge (k := F) (KaehlerDifferential.map C C A F ω)
      (KaehlerDifferential.map C C A F η)) = _
  rw [dependenceContraction_wedge, uniformizerFractionDifferentialDual_map,
    uniformizerFractionDifferentialDual_map]
  simp only [smul_sub, map_smul, map_sub, algebraMap_smul]

/-- The actual logarithmic mixed contraction identity; normalization of
the functional has already been proved in the preceding module. -/
theorem uniformizerScaledContraction_logarithmicMixed (π : A) (hπ : Irreducible π)
    (η : Ω[A⁄C]) :
    uniformizerScaledContraction C A F π hπ
      (logarithmicMixedTwoFormMap C A F π hπ η) =
      KaehlerDifferential.map C C A F
        (logarithmicMixedTwoFormPreimage C A π hπ η) := by
  let πF := algebraMap A F π
  have hπF : πF ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective A F)).mpr hπ.ne_zero
  have hlog : uniformizerFractionDifferentialDual C A F π hπ
      (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ)) =
      πF⁻¹ := by
    rw [logarithmicDifferential, map_smul]
    simp only [LogResidueCore.fractionUniformizerUnit_coe,
      uniformizerFractionDifferentialDual_D, smul_eq_mul, mul_one]
    rfl
  have hcoeff : πF * (algebraMap A F (uniformizerLocalDifferentialDual C A π hπ η) *
      πF⁻¹) = algebraMap A F (uniformizerLocalDifferentialDual C A π hπ η) := by
    rw [mul_left_comm, mul_inv_cancel₀ hπF, mul_one]
  change π • dependenceContraction (k := F) (E := Ω[F⁄C])
    (uniformizerFractionDifferentialDual C A F π hπ)
    (exteriorWedge (k := F)
      (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))
      (KaehlerDifferential.map C C A F η)) =
    KaehlerDifferential.map C C A F
      (η - uniformizerLocalDifferentialDual C A π hπ η • KaehlerDifferential.D C A π)
  rw [dependenceContraction_wedge, hlog, uniformizerFractionDifferentialDual_map,
    ← algebraMap_smul F π]
  simp only [logarithmicDifferential, LogResidueCore.fractionUniformizerUnit_coe,
    smul_sub, smul_smul]
  rw [show algebraMap A F π = πF from rfl, mul_inv_cancel₀ hπF, one_smul, hcoeff]
  rw [map_sub, map_smul, KaehlerDifferential.map_D]
  rw [algebraMap_smul F (uniformizerLocalDifferentialDual C A π hπ η)]

theorem uniformizerScaledContraction_comp_regularTwoFormMap (π : A) (hπ : Irreducible π) :
    (uniformizerScaledContraction C A F π hπ).comp (regularTwoFormMap C A F) =
      (KaehlerDifferential.map C C A F).comp (regularTwoFormPreimage C A π hπ) := by
  apply TensorProduct.ext
  apply LinearMap.ext
  intro ω
  apply LinearMap.ext
  intro η
  change uniformizerScaledContraction C A F π hπ
    (regularTwoFormMap C A F (ω ⊗ₜ[A] η)) =
      KaehlerDifferential.map C C A F (regularTwoFormPreimage C A π hπ (ω ⊗ₜ[A] η))
  rw [regularTwoFormMap_tmul, regularTwoFormPreimage_tmul]
  exact uniformizerScaledContraction_regularWedge C A F π hπ ω η

theorem uniformizerScaledContraction_comp_logarithmicMixed (π : A) (hπ : Irreducible π) :
    (uniformizerScaledContraction C A F π hπ).comp
      (logarithmicMixedTwoFormMap C A F π hπ) =
      (KaehlerDifferential.map C C A F).comp
        (logarithmicMixedTwoFormPreimage C A π hπ) := by
  apply LinearMap.ext
  intro η
  exact uniformizerScaledContraction_logarithmicMixed C A F π hπ η

/-- Actual scaled contraction lands in the actual regular image on the
whole actual logarithmic lattice, so its subsequent restriction is well-defined. -/
theorem uniformizerScaledContraction_mem_regularRange (π : A) (hπ : Irreducible π)
    (w : logarithmicTwoFormLattice C A F π hπ) :
    uniformizerScaledContraction C A F π hπ (w : ⋀[F]^2 Ω[F⁄C]) ∈
      LinearMap.range (KaehlerDifferential.map C C A F) := by
  obtain ⟨r, hr, s, hs, hrs⟩ := Submodule.mem_sup.mp w.property
  obtain ⟨u, rfl⟩ := hr
  obtain ⟨η, rfl⟩ := hs
  refine ⟨regularTwoFormPreimage C A π hπ u +
    logarithmicMixedTwoFormPreimage C A π hπ η, ?_⟩
  rw [map_add, ← hrs, map_add]
  exact congrArg₂ (fun x y : Ω[F⁄C] ↦ x + y)
    (LinearMap.congr_fun
      (uniformizerScaledContraction_comp_regularTwoFormMap C A F π hπ) u).symm
    (LinearMap.congr_fun
      (uniformizerScaledContraction_comp_logarithmicMixed C A F π hπ) η).symm

/-- The actual regular differential map is an equivalence onto its actual
image; its injectivity has been proved from smoothness and localization. -/
def regularDifferentialRangeEquiv :
    Ω[A⁄C] ≃ₗ[A] LinearMap.range (KaehlerDifferential.map C C A F) :=
  LinearEquiv.ofInjective _ (smooth_differential_fractionMap_injective C A F)

/-- Restrict an actual regular form to actual residue-field differentials. -/
def regularDifferentialRestriction :
    LinearMap.range (KaehlerDifferential.map C C A F) →ₗ[A]
      Ω[IsLocalRing.ResidueField A⁄C] :=
  (KaehlerDifferential.map C C A (IsLocalRing.ResidueField A)).comp
    (regularDifferentialRangeEquiv C A F).symm.toLinearMap

/-- The actual logarithmic two-form residue.  Its source is the actual
logarithmic A-lattice, and well-definedness is supplied by the proved
regular-range membership and the proved localization injectivity. -/
def logarithmicTwoFormResidue (π : A) (hπ : Irreducible π) :
    logarithmicTwoFormLattice C A F π hπ →ₗ[A] Ω[IsLocalRing.ResidueField A⁄C] :=
  (regularDifferentialRestriction C A F).comp
    (LinearMap.codRestrict (LinearMap.range (KaehlerDifferential.map C C A F))
      ((uniformizerScaledContraction C A F π hπ).comp
        (logarithmicTwoFormLattice C A F π hπ).subtype)
      (uniformizerScaledContraction_mem_regularRange C A F π hπ))

theorem logarithmicTwoFormResidue_eq_of_scaledContraction (π : A) (hπ : Irreducible π)
    (w : logarithmicTwoFormLattice C A F π hπ) (ω : Ω[A⁄C])
    (hω : uniformizerScaledContraction C A F π hπ (w : ⋀[F]^2 Ω[F⁄C]) =
      KaehlerDifferential.map C C A F ω) :
    logarithmicTwoFormResidue C A F π hπ w =
      KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ω := by
  change KaehlerDifferential.map C C A (IsLocalRing.ResidueField A)
      ((regularDifferentialRangeEquiv C A F).symm _) =
    KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ω
  congr 1
  apply (regularDifferentialRangeEquiv C A F).injective
  rw [LinearEquiv.apply_symm_apply]
  apply Subtype.ext
  exact hω

/-- The constructed residue annihilates genuine regular two-forms. -/
@[simp]
theorem logarithmicTwoFormResidue_regular (π : A) (hπ : Irreducible π)
    (ω η : Ω[A⁄C]) :
    logarithmicTwoFormResidue C A F π hπ
      ⟨regularTwoFormMap C A F (ω ⊗ₜ[A] η),
        regularTwoFormMap_mem_lattice C A F π hπ (ω ⊗ₜ[A] η)⟩ = 0 := by
  let w : logarithmicTwoFormLattice C A F π hπ :=
    ⟨regularTwoFormMap C A F (ω ⊗ₜ[A] η),
      regularTwoFormMap_mem_lattice C A F π hπ (ω ⊗ₜ[A] η)⟩
  let ζ : Ω[A⁄C] := π • (uniformizerLocalDifferentialDual C A π hπ ω • η -
    uniformizerLocalDifferentialDual C A π hπ η • ω)
  have hw : uniformizerScaledContraction C A F π hπ (w : ⋀[F]^2 Ω[F⁄C]) =
      KaehlerDifferential.map C C A F ζ := by
    change uniformizerScaledContraction C A F π hπ
      (regularTwoFormMap C A F (ω ⊗ₜ[A] η)) = KaehlerDifferential.map C C A F ζ
    rw [regularTwoFormMap_tmul]
    exact uniformizerScaledContraction_regularWedge C A F π hπ ω η
  have hr : logarithmicTwoFormResidue C A F π hπ w =
      KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ζ :=
    logarithmicTwoFormResidue_eq_of_scaledContraction C A F π hπ w ζ hw
  have hπκ : algebraMap A (IsLocalRing.ResidueField A) π = 0 :=
    (IsLocalRing.residue_eq_zero_iff π).mpr (uniformizer_mem_maximalIdeal A π hπ)
  have hζ : KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ζ = 0 := by
    change KaehlerDifferential.map C C A (IsLocalRing.ResidueField A)
      (π • (uniformizerLocalDifferentialDual C A π hπ ω • η -
        uniformizerLocalDifferentialDual C A π hπ η • ω)) = 0
    rw [map_smul, ← algebraMap_smul (IsLocalRing.ResidueField A) π, hπκ, zero_smul]
  exact hr.trans hζ

/-- The constructed residue of the actual uniformizer logarithmic form
wedged with an actual regular form is its actual residue-field restriction. -/
@[simp]
theorem logarithmicTwoFormResidue_mixed (π : A) (hπ : Irreducible π)
    (η : Ω[A⁄C]) :
    logarithmicTwoFormResidue C A F π hπ
      ⟨logarithmicMixedTwoFormMap C A F π hπ η,
        logarithmicMixedTwoFormMap_mem_lattice C A F π hπ η⟩ =
      KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) η := by
  let w : logarithmicTwoFormLattice C A F π hπ :=
    ⟨logarithmicMixedTwoFormMap C A F π hπ η,
      logarithmicMixedTwoFormMap_mem_lattice C A F π hπ η⟩
  let ζ : Ω[A⁄C] := logarithmicMixedTwoFormPreimage C A π hπ η
  have hw : uniformizerScaledContraction C A F π hπ (w : ⋀[F]^2 Ω[F⁄C]) =
      KaehlerDifferential.map C C A F ζ := by
    exact uniformizerScaledContraction_logarithmicMixed C A F π hπ η
  have hr : logarithmicTwoFormResidue C A F π hπ w =
      KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ζ :=
    logarithmicTwoFormResidue_eq_of_scaledContraction C A F π hπ w ζ hw
  have hπκ : algebraMap A (IsLocalRing.ResidueField A) π = 0 :=
    (IsLocalRing.residue_eq_zero_iff π).mpr (uniformizer_mem_maximalIdeal A π hπ)
  have hζ : KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) ζ =
      KaehlerDifferential.map C C A (IsLocalRing.ResidueField A) η := by
    change KaehlerDifferential.map C C A (IsLocalRing.ResidueField A)
      (logarithmicMixedTwoFormPreimage C A π hπ η) = _
    simp only [logarithmicMixedTwoFormPreimage_apply, map_sub, map_smul,
      KaehlerDifferential.map_D, hπκ, map_zero, smul_zero, sub_zero]
  exact hr.trans hζ

end ActualLogarithmicTwoForms

end ChenRanks
