import ChenRanks.DVRNormalizedDifferential
import ChenRanks.DVRUnitOrder

/-!
# Actual scalar residues of logarithmic one-forms

The domain is the actual A-submodule of the actual field Kähler module
generated by the actual regular image and the uniformizer logarithmic
form. A normalized differential dual is already constructed and proved
in DVRNormalizedDifferential. Multiplication by the actual uniformizer
carries this lattice into the actual scalar image of A in F. Inverting
that actual injective scalar map and reducing to the actual residue field
constructs the residue. Its value on a fraction's logarithmic differential
is the actual normalized valuation order.

This is the one-form residue required in the paper's logarithmic-kernel
lemma. Actual smooth local rings remain to be supplied by the model.
-/

noncomputable section

open scoped BigOperators

namespace ChenRanks

variable (C A F : Type*) [Field C] [CharZero C] [CommRing A] [IsDomain A] [Field F]
  [Algebra C A] [Algebra C F] [Algebra A F] [IsScalarTower C A F]
  [IsFractionRing A F] [IsDiscreteValuationRing A] [Algebra.EssFiniteType C A]
  [Algebra.FormallySmooth C A]

/-- Actual local scalar multiples of the actual uniformizer logarithmic form. -/
def uniformizerLogOneFormMap (π : A) (hπ : Irreducible π) : A →ₗ[A] Ω[F⁄C] :=
  LinearMap.toSpanSingleton A Ω[F⁄C]
    (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ))

/-- The actual logarithmic one-form lattice. -/
abbrev logarithmicOneFormLattice (π : A) (hπ : Irreducible π) : Submodule A Ω[F⁄C] :=
  LinearMap.range (KaehlerDifferential.map C C A F) ⊔
    LinearMap.range (uniformizerLogOneFormMap C A F π hπ)

/-- The actual normalized dual scaled by the uniformizer. -/
def uniformizerScaledOneFormDual (π : A) (hπ : Irreducible π) : Ω[F⁄C] →ₗ[A] F :=
  π • (uniformizerFractionDifferentialDual C A F π hπ).restrictScalars A

/-- On an actual regular form, the scaled dual is an actual local scalar
which is divisible by the uniformizer. -/
theorem uniformizerScaledOneFormDual_regular (π : A) (hπ : Irreducible π)
    (ω : Ω[A⁄C]) :
    uniformizerScaledOneFormDual C A F π hπ (KaehlerDifferential.map C C A F ω) =
      algebraMap A F (π * uniformizerLocalDifferentialDual C A π hπ ω) := by
  change π • uniformizerFractionDifferentialDual C A F π hπ
    (KaehlerDifferential.map C C A F ω) = _
  rw [uniformizerFractionDifferentialDual_map, Algebra.smul_def, map_mul]

/-- On an actual local multiple of dlog π the scaled dual is exactly
that multiple's actual scalar image. -/
theorem uniformizerScaledOneFormDual_logarithmic (π : A) (hπ : Irreducible π)
    (a : A) :
    uniformizerScaledOneFormDual C A F π hπ (uniformizerLogOneFormMap C A F π hπ a) =
      algebraMap A F a := by
  have hπF : algebraMap A F π ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective A F)).mpr hπ.ne_zero
  have hlog : uniformizerFractionDifferentialDual C A F π hπ
      (logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ)) =
      (algebraMap A F π)⁻¹ := by
    rw [logarithmicDifferential, map_smul]
    simp only [LogResidueCore.fractionUniformizerUnit_coe,
      uniformizerFractionDifferentialDual_D, smul_eq_mul, mul_one]
  change π • (uniformizerFractionDifferentialDual C A F π hπ).restrictScalars A
    (a • logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ)) = _
  rw [map_smul]
  simp only [LinearMap.restrictScalars_apply, Algebra.smul_def]
  rw [hlog]
  field_simp

/-- The entire actual lattice maps into the actual image of local scalars. -/
theorem uniformizerScaledOneFormDual_mem_scalarRange (π : A) (hπ : Irreducible π)
    (w : logarithmicOneFormLattice C A F π hπ) :
    uniformizerScaledOneFormDual C A F π hπ w ∈ LinearMap.range (Algebra.linearMap A F) := by
  obtain ⟨r, hr, t, ht, hrt⟩ := Submodule.mem_sup.mp w.property
  obtain ⟨ω, rfl⟩ := hr
  obtain ⟨a, rfl⟩ := ht
  refine ⟨π * uniformizerLocalDifferentialDual C A π hπ ω + a, ?_⟩
  change algebraMap A F (_ + _) = _
  rw [map_add, ← hrt, map_add, uniformizerScaledOneFormDual_regular,
    uniformizerScaledOneFormDual_logarithmic]

/-- The actual local scalar embedding is equivalent to its actual image. -/
def localScalarRangeEquiv : A ≃ₗ[A] LinearMap.range (Algebra.linearMap A F) :=
  LinearEquiv.ofInjective _ (IsFractionRing.injective A F)

/-- The actual residue, with the actual logarithmic lattice as domain. -/
def logarithmicOneFormResidue (π : A) (hπ : Irreducible π) :
    logarithmicOneFormLattice C A F π hπ →ₗ[A] IsLocalRing.ResidueField A :=
  (Algebra.linearMap A (IsLocalRing.ResidueField A)).comp
    ((localScalarRangeEquiv A F).symm.toLinearMap.comp
      (((uniformizerScaledOneFormDual C A F π hπ).comp
        (logarithmicOneFormLattice C A F π hπ).subtype).codRestrict
          (LinearMap.range (Algebra.linearMap A F))
          (uniformizerScaledOneFormDual_mem_scalarRange C A F π hπ)))

/-- The residue evaluates any proved local scalar preimage by reduction. -/
theorem logarithmicOneFormResidue_eq_of_scaledDual (π : A) (hπ : Irreducible π)
    (w : logarithmicOneFormLattice C A F π hπ) (a : A)
    (ha : uniformizerScaledOneFormDual C A F π hπ w = algebraMap A F a) :
    logarithmicOneFormResidue C A F π hπ w = IsLocalRing.residue A a := by
  change IsLocalRing.residue A ((localScalarRangeEquiv A F).symm _) = _
  congr 1
  apply (localScalarRangeEquiv A F).injective
  rw [LinearEquiv.apply_symm_apply]
  apply Subtype.ext
  exact ha

/-- Actual regular forms lie in the actual lattice. -/
def regularOneFormInLogarithmicLattice (π : A) (hπ : Irreducible π)
    (ω : Ω[A⁄C]) : logarithmicOneFormLattice C A F π hπ :=
  ⟨KaehlerDifferential.map C C A F ω, Submodule.mem_sup_left ⟨ω, rfl⟩⟩

/-- Actual local logarithmic multiples lie in the actual lattice. -/
def uniformizerOneFormInLogarithmicLattice (π : A) (hπ : Irreducible π)
    (a : A) : logarithmicOneFormLattice C A F π hπ :=
  ⟨uniformizerLogOneFormMap C A F π hπ a, Submodule.mem_sup_right ⟨a, rfl⟩⟩

/-- The constructed residue annihilates actual regular forms. -/
@[simp] theorem logarithmicOneFormResidue_regular (π : A) (hπ : Irreducible π)
    (ω : Ω[A⁄C]) :
    logarithmicOneFormResidue C A F π hπ (regularOneFormInLogarithmicLattice C A F π hπ ω) = 0 := by
  have hscaled := uniformizerScaledOneFormDual_regular C A F π hπ ω
  have hres := logarithmicOneFormResidue_eq_of_scaledDual C A F π hπ
    (regularOneFormInLogarithmicLattice C A F π hπ ω)
    (π * uniformizerLocalDifferentialDual C A π hπ ω) hscaled
  rw [hres, map_mul]
  rw [(IsLocalRing.residue_eq_zero_iff π).mpr (uniformizer_mem_maximalIdeal A π hπ), zero_mul]

/-- The constructed residue sends a·dlog π to the actual residue of a. -/
@[simp] theorem logarithmicOneFormResidue_uniformizer (π : A) (hπ : Irreducible π)
    (a : A) :
    logarithmicOneFormResidue C A F π hπ
      (uniformizerOneFormInLogarithmicLattice C A F π hπ a) = IsLocalRing.residue A a :=
  logarithmicOneFormResidue_eq_of_scaledDual C A F π hπ _ a
    (uniformizerScaledOneFormDual_logarithmic C A F π hπ a)

omit [CharZero C] [Algebra.EssFiniteType C A] [Algebra.FormallySmooth C A] in
/-- Actual logarithmic differentials of arbitrary fractions lie in the lattice. -/
theorem fractionLogarithmicOneForm_mem_lattice (π : A) (hπ : Irreducible π) (f : Fˣ) :
    logarithmicDifferential C F f ∈ logarithmicOneFormLattice C A F π hπ := by
  obtain ⟨ω, hω⟩ := exists_logarithmicDifferential_uniformizer_order_decomposition C A F π hπ f
  rw [hω]
  apply (logarithmicOneFormLattice C A F π hπ).add_mem
  · have h : uniformizerLogOneFormMap C A F π hπ 1 =
        logarithmicDifferential C F (LogResidueCore.fractionUniformizerUnit A F π hπ) := by
      simp [uniformizerLogOneFormMap]
    rw [← h]
    exact_mod_cast (logarithmicOneFormLattice C A F π hπ).smul_mem
      (localDVRUnitOrder A F f : A) (Submodule.mem_sup_right ⟨1, rfl⟩)
  · exact Submodule.mem_sup_left ⟨ω, rfl⟩

/-- The actual fraction logarithmic form as an actual lattice element. -/
def fractionOneFormInLogarithmicLattice (π : A) (hπ : Irreducible π) (f : Fˣ) :
    logarithmicOneFormLattice C A F π hπ :=
  ⟨logarithmicDifferential C F f, fractionLogarithmicOneForm_mem_lattice C A F π hπ f⟩

/-- The residue of the actual logarithmic differential of an actual
fraction is its actual normalized integer order. -/
theorem logarithmicOneFormResidue_fraction (π : A) (hπ : Irreducible π) (f : Fˣ) :
    logarithmicOneFormResidue C A F π hπ
      (fractionOneFormInLogarithmicLattice C A F π hπ f) =
      (localDVRUnitOrder A F f : IsLocalRing.ResidueField A) := by
  letI : AddCommGroup (logarithmicOneFormLattice C A F π hπ) := Submodule.addCommGroup _
  obtain ⟨ω, hω⟩ := exists_logarithmicDifferential_uniformizer_order_decomposition C A F π hπ f
  have hs : fractionOneFormInLogarithmicLattice C A F π hπ f =
      (localDVRUnitOrder A F f : A) • uniformizerOneFormInLogarithmicLattice C A F π hπ 1 +
        regularOneFormInLogarithmicLattice C A F π hπ ω := by
    apply Subtype.ext
    simpa only [uniformizerOneFormInLogarithmicLattice, uniformizerLogOneFormMap,
      LinearMap.toSpanSingleton_apply, one_smul, Int.cast_smul_eq_zsmul] using hω
  rw [hs, map_add, map_smul, logarithmicOneFormResidue_regular,
    logarithmicOneFormResidue_uniformizer, map_one, add_zero]
  simp only [Algebra.smul_def, map_intCast, mul_one]

/-- An actual finite relation of actual logarithmic forms implies the
actual valuation-order relation after applying the constructed residue. -/
theorem logarithmicOneForm_relation_orders {ι : Type*} (s : Finset ι)
    (π : A) (hπ : Irreducible π) (a : ι → A) (f : ι → Fˣ)
    (h : ∑ i ∈ s, a i • logarithmicDifferential C F (f i) = 0) :
    ∑ i ∈ s, a i • (localDVRUnitOrder A F (f i) : IsLocalRing.ResidueField A) = 0 := by
  have hs : ∑ i ∈ s, a i • fractionOneFormInLogarithmicLattice C A F π hπ (f i) = 0 := by
    apply Subtype.ext
    change (logarithmicOneFormLattice C A F π hπ).subtype
      (∑ i ∈ s, a i • fractionOneFormInLogarithmicLattice C A F π hπ (f i)) = 0
    simpa only [map_sum, map_smul, fractionOneFormInLogarithmicLattice] using h
  have hr := congrArg (logarithmicOneFormResidue C A F π hπ) hs
  simpa only [map_sum, map_smul, logarithmicOneFormResidue_fraction, map_zero] using hr

end ChenRanks
