import ChenRanks.MixedUniverseFiniteTypeClosedPoints
import ChenRanks.KoszulResonanceSupport
import ChenRanks.KoszulProjectiveQuotientMap
import Mathlib.RingTheory.Spectrum.Prime.Jacobson
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import Mathlib.LinearAlgebra.Dual.Lemmas

/-!
# Actual nonzero symmetric-dual specializations in independent universes

All rings are the original symmetric algebra on the original dual space.
Pure finite-type algebra constructs the scalar points of actual maximal
ideals. Restriction to actual generators and the native double-dual
equivalence reconstruct the original vector. Actual ring Jacobsonness
then gives nonzero evaluation specializations above actual punctured
primes. The native irrelevant ideal is proved to be the actual generator
ideal, so every native relevant prime has such a specialization.

No scalar Scheme morphism between different universes, point detector,
maximal ideal, or desired vector evaluation is an input.
-/

noncomputable section

open scoped TensorProduct
open TopologicalSpace

namespace ChenRanks.Koszul

variable (k : Type*) [Field k]
variable (E : Type*) [AddCommGroup E] [_root_.Module k E]

/-- The actual ideal of the origin, generated by the original degree-one
symmetric generators, with independent base and vector-space universes. -/
def mixedUniverseSymmetricDualOriginIdeal : Ideal (S k (_root_.Module.Dual k E)) :=
  Ideal.span (Set.range (SymmetricAlgebra.ι k (_root_.Module.Dual k E)))

/-- The actual punctured affine spectrum of the original symmetric ring. -/
def mixedUniverseSymmetricDualPuncturedOpen :
    TopologicalSpace.Opens (PrimeSpectrum (S k (_root_.Module.Dual k E))) :=
  ⟨(PrimeSpectrum.zeroLocus (mixedUniverseSymmetricDualOriginIdeal k E :
      Set (S k (_root_.Module.Dual k E)))).compl,
    (PrimeSpectrum.isClosed_zeroLocus _).isOpen_compl⟩

section FiniteDimensional

variable [FiniteDimensional k E]

/-- True vector evaluation is outside the actual origin precisely when
the original vector is nonzero. -/
theorem mixedUniverse_vectorEvaluationPrime_mem_punctured_iff (e : E) :
    vectorEvaluationPrime k E e ∈ mixedUniverseSymmetricDualPuncturedOpen k E ↔
      e ≠ 0 := by
  change ¬ mixedUniverseSymmetricDualOriginIdeal k E ≤
      pointEvaluationKernel k (_root_.Module.Dual k E) (pointOfVector k E e) ↔ e ≠ 0
  constructor
  · intro h he
    apply h
    apply Ideal.span_le.mpr
    rintro s ⟨φ, rfl⟩
    change pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) = 0
    simp only [pointEvaluation, SymmetricAlgebra.lift_ι_apply, pointOfVector,
      he, map_zero, LinearMap.zero_apply]
  · intro he h
    apply pointOfVector_ne_zero k E he
    apply LinearMap.ext
    intro φ
    have hφ := h (Ideal.subset_span (Set.mem_range_self φ))
    change pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) = 0 at hφ
    simpa only [pointEvaluation, SymmetricAlgebra.lift_ι_apply,
      LinearMap.zero_apply] using hφ

/-- Finite type of the actual symmetric ring follows from its genuine
finite-basis polynomial equivalence in independent universes. -/
theorem mixedUniverse_symmetricDual_finiteType :
    Algebra.FiniteType k (S k (_root_.Module.Dual k E)) := by
  let b := _root_.Module.finBasis k (_root_.Module.Dual k E)
  let e := SymmetricAlgebra.equivMvPolynomial b
  exact Algebra.FiniteType.of_surjective e.symm.toAlgHom e.symm.surjective

variable [IsAlgClosed k]

/-- The original maximal ideal is precisely the original vector's
actual evaluation kernel, reconstructed from a true scalar algebra map. -/
theorem mixedUniverse_symmetricDual_maximalIdeal_exists_vector
    (m : Ideal (S k (_root_.Module.Dual k E))) (hm : m.IsMaximal) :
    ∃ e : E, pointEvaluationKernel k (_root_.Module.Dual k E)
      (pointOfVector k E e) = m := by
  letI := mixedUniverse_symmetricDual_finiteType k E
  obtain ⟨a, ha⟩ := ChenRanks.finiteType_maximalIdeal_exists_scalar_point (k := k) m hm
  let v : _root_.Module.Dual k (_root_.Module.Dual k E) :=
    a.toLinearMap.comp (SymmetricAlgebra.ι k (_root_.Module.Dual k E))
  let e : E := (_root_.Module.evalEquiv k E).symm v
  have hvector : pointOfVector k E e = v := by
    change _root_.Module.evalEquiv k E e = v
    exact (_root_.Module.evalEquiv k E).apply_symm_apply v
  have heval : pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e) = a := by
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro φ
    change SymmetricAlgebra.lift (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) =
        a (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ)
    rw [SymmetricAlgebra.lift_ι_apply]
    exact congrArg (fun f : _root_.Module.Dual k (_root_.Module.Dual k E) ↦ f φ) hvector
  refine ⟨e, ?_⟩
  change RingHom.ker (pointEvaluation k (_root_.Module.Dual k E)
    (pointOfVector k E e)).toRingHom = m
  rw [heval]
  exact ha

/-- Every actual punctured prime has a genuine nonzero original-vector
evaluation specialization above it; ring Jacobsonness supplies the point. -/
theorem mixedUniverse_symmetricDual_puncturedPrime_exists_nonzero_evaluation_specialization
    (q : PrimeSpectrum (S k (_root_.Module.Dual k E)))
    (hq : q ∈ mixedUniverseSymmetricDualPuncturedOpen k E) :
    ∃ e : E, e ≠ 0 ∧ q.asIdeal ≤
      pointEvaluationKernel k (_root_.Module.Dual k E) (pointOfVector k E e) := by
  let R := S k (_root_.Module.Dual k E)
  letI : Algebra.FiniteType k R := mixedUniverse_symmetricDual_finiteType k E
  letI : IsJacobsonRing R := isJacobsonRing_of_finiteType (A := k)
  let U : Set (PrimeSpectrum R) := mixedUniverseSymmetricDualPuncturedOpen k E
  let Z : Set (PrimeSpectrum R) := U ∩ PrimeSpectrum.zeroLocus (q.asIdeal : Set R)
  have hZ : Z.Nonempty := ⟨q, hq, Set.Subset.rfl⟩
  have hZlocally : IsLocallyClosed Z :=
    (mixedUniverseSymmetricDualPuncturedOpen k E).isOpen.isLocallyClosed.inter
      (PrimeSpectrum.isClosed_zeroLocus _).isLocallyClosed
  obtain ⟨m, hmZ, hmclosed⟩ := nonempty_inter_closedPoints hZ hZlocally
  have hm : m.asIdeal.IsMaximal :=
    (PrimeSpectrum.isClosed_singleton_iff_isMaximal m).mp hmclosed
  obtain ⟨e, hem⟩ := mixedUniverse_symmetricDual_maximalIdeal_exists_vector k E m.asIdeal hm
  have heq : vectorEvaluationPrime k E e = m := PrimeSpectrum.ext hem
  have he : e ≠ 0 :=
    (mixedUniverse_vectorEvaluationPrime_mem_punctured_iff k E e).mp
      (heq.symm ▸ hmZ.1)
  refine ⟨e, he, ?_⟩
  have hqm : q.asIdeal ≤ m.asIdeal := hmZ.2
  rw [← hem] at hqm
  exact hqm

end FiniteDimensional

variable {ι : Type*} [Fintype ι]
  (b : _root_.Module.Basis ι k (_root_.Module.Dual k E))

omit [Fintype ι] in
/-- The true multiplication differential lands in the actual degree-one
generator ideal, by real tensor induction. -/
theorem mixedUniverse_delta1_mem_symmetricDualOriginIdeal
    (z : C1 k (_root_.Module.Dual k E)) :
    delta1 k (_root_.Module.Dual k E) z ∈ mixedUniverseSymmetricDualOriginIdeal k E := by
  induction z using TensorProduct.induction_on with
  | zero => exact Ideal.zero_mem _
  | add x y hx hy =>
    rw [map_add]
    exact Ideal.add_mem _ hx hy
  | tmul s φ =>
    rw [delta1_tmul]
    exact Ideal.mul_mem_left _ s (Ideal.subset_span (Set.mem_range_self φ))

/-- The native irrelevant ideal equals the original actual generator ideal. -/
theorem mixedUniverse_homogeneousS_irrelevant_toIdeal_eq_origin :
    (HomogeneousIdeal.irrelevant (homogeneousS k (_root_.Module.Dual k E) b)).toIdeal =
      mixedUniverseSymmetricDualOriginIdeal k E := by
  apply le_antisymm
  · apply (HomogeneousIdeal.toIdeal_irrelevant_le _).mpr
    intro n hn s hs
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
    obtain ⟨z, hz⟩ := multiplicationAtDegree_surjective k (_root_.Module.Dual k E) b m
      (⟨s, hs⟩ : homogeneousS k (_root_.Module.Dual k E) b (m + 1))
    have hz' : delta1 k (_root_.Module.Dual k E) z.val = s := congrArg Subtype.val hz
    rw [← hz']
    exact mixedUniverse_delta1_mem_symmetricDualOriginIdeal k E z.val
  · apply Ideal.span_le.mpr
    rintro s ⟨φ, rfl⟩
    exact HomogeneousIdeal.mem_irrelevant_of_mem _ (by decide)
      (homogeneousS_ι k (_root_.Module.Dual k E) b φ)

variable [FiniteDimensional k E] [IsAlgClosed k]

/-- Every actual native relevant homogeneous prime has a true nonzero
original-vector specialization in the same original symmetric ring. -/
theorem mixedUniverse_symmetricDual_projectivePrime_exists_nonzero_evaluation_specialization
    (q : ProjectiveSpectrum (homogeneousS k (_root_.Module.Dual k E) b)) :
    ∃ e : E, e ≠ 0 ∧ q.asHomogeneousIdeal.toIdeal ≤
      pointEvaluationKernel k (_root_.Module.Dual k E) (pointOfVector k E e) := by
  let p : PrimeSpectrum (S k (_root_.Module.Dual k E)) :=
    ⟨q.asHomogeneousIdeal.toIdeal, q.isPrime⟩
  have hp : p ∈ mixedUniverseSymmetricDualPuncturedOpen k E := by
    change ¬ mixedUniverseSymmetricDualOriginIdeal k E ≤ q.asHomogeneousIdeal.toIdeal
    rw [← mixedUniverse_homogeneousS_irrelevant_toIdeal_eq_origin k E b]
    exact q.not_irrelevant_le
  exact mixedUniverse_symmetricDual_puncturedPrime_exists_nonzero_evaluation_specialization
    k E p hp

end ChenRanks.Koszul
