import ChenRanks.KoszulMetabelianLieModel
import ChenRanks.MetabelianAdjointSymmetricAction
import Mathlib.Algebra.Lie.Free
import Mathlib.Algebra.Lie.Quotient

/-!
# The actual basis-linear quadratic metabelian free-Lie quotient

Mathlib's free Lie algebra is free on the original basis index set, not
on the set of all vectors. The actual basis constructs the linear
generator map from `V`. The native ideal generated by its original
quadratic relations, together with the native second derived ideal,
defines the genuine quotient below. Its metabelianity is proved via the
actual surjective quotient Lie homomorphism. Thus the polynomial adjoint
action constructed in `MetabelianAdjointSymmetricAction` is instantiated
without a new metabelian or commuting-operator hypothesis.

The genuine free-Lie universal property constructs a map to the original
Koszul Lie model. Both quadratic and second-derived relations are proved
to lie in its actual kernel. This is a proved map, not yet an assertion
that this map is an isomorphism or a Chen comparison.
-/

noncomputable section

namespace ChenRanks.LieComparison

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [Module k V]
variable {ι : Type*} (b : _root_.Module.Basis ι k V)
variable (K : Submodule k (⋀[k]^2 V))

/-- The genuine vector-linear generator map to the free Lie algebra on
the actual basis index set. -/
def freeVectorGenerators : V →ₗ[k] FreeLieAlgebra k ι :=
  b.constr k (FreeLieAlgebra.of k)

@[simp]
theorem freeVectorGenerators_basis (i : ι) :
    freeVectorGenerators k V b (b i) = FreeLieAlgebra.of k i :=
  b.constr_basis k (FreeLieAlgebra.of k) i

/-- The actual alternating generator bracket before exterior descent. -/
def freeGeneratorBracketAlternating : V [⋀^Fin 2]→ₗ[k] FreeLieAlgebra k ι where
  toFun a := ⁅freeVectorGenerators k V b (a 0), freeVectorGenerators k V b (a 1)⁆
  map_update_add' a i x y := by
    fin_cases i <;> simp [Function.update, map_add, add_lie, lie_add]
  map_update_smul' a i c x := by
    fin_cases i <;> simp [Function.update, map_smul, smul_lie, LieAlgebra.lie_smul]
  map_eq_zero_of_eq' a i j h hij := by
    fin_cases i <;> fin_cases j
    · exact (hij rfl).elim
    · change a 0 = a 1 at h
      change ⁅freeVectorGenerators k V b (a 0), freeVectorGenerators k V b (a 1)⁆ = 0
      rw [h, lie_self]
    · change a 1 = a 0 at h
      change ⁅freeVectorGenerators k V b (a 0), freeVectorGenerators k V b (a 1)⁆ = 0
      rw [h, lie_self]
    · exact (hij rfl).elim

/-- The actual linear exterior-square map of original generator brackets. -/
def freeGeneratorBracket : (⋀[k]^2 V) →ₗ[k] FreeLieAlgebra k ι :=
  exteriorPower.alternatingMapLinearEquiv (freeGeneratorBracketAlternating k V b)

@[simp]
theorem freeGeneratorBracket_exteriorWedge (u v : V) :
    freeGeneratorBracket k V b (exteriorWedge u v) =
      ⁅freeVectorGenerators k V b u, freeVectorGenerators k V b v⁆ := by
  simp only [freeGeneratorBracket, exteriorWedge,
    exteriorPower.alternatingMapLinearEquiv_apply_ιMulti]
  rfl

/-- The native Lie ideal generated by the original quadratic subspace. -/
def quadraticRelationIdeal : LieIdeal k (FreeLieAlgebra k ι) :=
  LieSubmodule.lieSpan k (FreeLieAlgebra k ι)
    (Set.range fun w : K => freeGeneratorBracket k V b (w : ⋀[k]^2 V))

/-- The original quadratic relations and the original second derived
ideal, inside the actual free Lie algebra. -/
def quadraticMetabelianRelationIdeal : LieIdeal k (FreeLieAlgebra k ι) :=
  quadraticRelationIdeal k V b K ⊔ LieAlgebra.derivedSeries k (FreeLieAlgebra k ι) 2

/-- The genuine native quotient by the actual relation ideal. -/
abbrev QuadraticMetabelianFreeQuotient :=
  FreeLieAlgebra k ι ⧸ quadraticMetabelianRelationIdeal k V b K

/-- The true quotient projection as a Lie homomorphism. -/
def quadraticMetabelianProjection :
    FreeLieAlgebra k ι →ₗ⁅k⁆ QuadraticMetabelianFreeQuotient k V b K where
  __ := (quadraticMetabelianRelationIdeal k V b K).toSubmodule.mkQ
  map_lie' := by intro x y; rfl

theorem quadraticMetabelianProjection_surjective :
    Function.Surjective (quadraticMetabelianProjection k V b K) :=
  Submodule.mkQ_surjective (quadraticMetabelianRelationIdeal k V b K).toSubmodule

@[simp]
theorem quadraticMetabelianProjection_eq_zero_iff (x : FreeLieAlgebra k ι) :
    quadraticMetabelianProjection k V b K x = 0 ↔
      x ∈ quadraticMetabelianRelationIdeal k V b K :=
  Submodule.Quotient.mk_eq_zero _

theorem quadraticMetabelianProjection_ker :
    (quadraticMetabelianProjection k V b K).ker =
      quadraticMetabelianRelationIdeal k V b K := by
  ext x
  exact quadraticMetabelianProjection_eq_zero_iff k V b K x

/-- Native second-derived vanishing is proved for this actual quotient. -/
theorem quadraticMetabelianFreeQuotient_derived_two_eq_bot :
    LieAlgebra.derivedSeries k (QuadraticMetabelianFreeQuotient k V b K) 2 = ⊥ := by
  rw [← LieIdeal.derivedSeries_map_eq
    (f := quadraticMetabelianProjection k V b K) 2
      (quadraticMetabelianProjection_surjective k V b K)]
  apply LieIdeal.map_eq_bot_iff.mpr
  rw [quadraticMetabelianProjection_ker]
  exact le_sup_right

/-- Actual vector generators in the original native quotient. -/
def quadraticMetabelianGenerators :
    V →ₗ[k] QuadraticMetabelianFreeQuotient k V b K :=
  (quadraticMetabelianProjection k V b K).toLinearMap.comp (freeVectorGenerators k V b)

@[simp]
theorem quadraticMetabelianGenerators_basis (i : ι) :
    quadraticMetabelianGenerators k V b K (b i) =
      quadraticMetabelianProjection k V b K (FreeLieAlgebra.of k i) := by
  simp only [quadraticMetabelianGenerators, LinearMap.comp_apply,
    freeVectorGenerators_basis]
  rfl

/-- The genuine adjoint polynomial action for the actual free-Lie quotient.
The metabelian condition is discharged internally by the preceding theorem. -/
def quadraticMetabelianPolynomialAction :
    SymmetricAlgebra k V →ₐ[k]
      Module.End k (ActualDerivedIdeal k (QuadraticMetabelianFreeQuotient k V b K)) :=
  symmetricAdjointAction k (QuadraticMetabelianFreeQuotient k V b K) V
    (quadraticMetabelianGenerators k V b K)
    (quadraticMetabelianFreeQuotient_derived_two_eq_bot k V b K)

theorem quadraticMetabelianPolynomialAction_generator (u : V)
    (d : ActualDerivedIdeal k (QuadraticMetabelianFreeQuotient k V b K)) :
    quadraticMetabelianPolynomialAction k V b K (SymmetricAlgebra.ι k V u) d =
      ⁅quadraticMetabelianGenerators k V b K u, d⁆ := by
  rw [quadraticMetabelianPolynomialAction, symmetricAdjointAction_ι]
  rfl

/-- The original free-Lie universal property applied to the actual model's generators. -/
def freeLieToKoszulModel :
    FreeLieAlgebra k ι →ₗ⁅k⁆ Koszul.MetabelianLieModel k V K :=
  FreeLieAlgebra.lift k (fun i => Koszul.MetabelianLieModel.generatorInclusion k V K (b i))

theorem freeLieToKoszulModel_generator (u : V) :
    freeLieToKoszulModel k V b K (freeVectorGenerators k V b u) =
      Koszul.MetabelianLieModel.generatorInclusion k V K u := by
  have h : (freeLieToKoszulModel k V b K).toLinearMap.comp (freeVectorGenerators k V b) =
      Koszul.MetabelianLieModel.generatorInclusion k V K := by
    apply b.ext
    intro i
    simp only [LinearMap.comp_apply, freeVectorGenerators_basis]
    change (FreeLieAlgebra.lift k
      (fun i => Koszul.MetabelianLieModel.generatorInclusion k V K (b i)))
      (FreeLieAlgebra.of k i) = _
    exact FreeLieAlgebra.lift_of_apply _ i
  exact LinearMap.congr_fun h u

theorem freeLieToKoszulModel_bracket :
    (freeLieToKoszulModel k V b K).toLinearMap.comp (freeGeneratorBracket k V b) =
      Koszul.MetabelianLieModel.generatorBracketMap k V K := by
  apply exteriorPower.linearMap_ext
  apply DFunLike.ext
  intro a
  have ha : exteriorPower.ιMulti k 2 a = exteriorWedge (a 0) (a 1) := by
    change exteriorPower.ιMulti k 2 a = exteriorPower.ιMulti k 2 ![a 0, a 1]
    congr 1
    funext i
    fin_cases i <;> rfl
  change freeLieToKoszulModel k V b K (freeGeneratorBracket k V b (exteriorPower.ιMulti k 2 a)) =
    Koszul.MetabelianLieModel.generatorBracketMap k V K (exteriorPower.ιMulti k 2 a)
  rw [ha, freeGeneratorBracket_exteriorWedge,
    Koszul.MetabelianLieModel.generatorBracketMap_exteriorWedge,
    LieHom.map_lie, freeLieToKoszulModel_generator, freeLieToKoszulModel_generator]

/-- The original quadratic relations actually lie in the constructed map's kernel. -/
theorem quadraticRelationIdeal_le_freeLieToKoszulModel_ker :
    quadraticRelationIdeal k V b K ≤ (freeLieToKoszulModel k V b K).ker := by
  apply LieSubmodule.lieSpan_le.mpr
  rintro x ⟨w, rfl⟩
  change freeLieToKoszulModel k V b K (freeGeneratorBracket k V b (w : ⋀[k]^2 V)) = 0
  have h := LinearMap.congr_fun (freeLieToKoszulModel_bracket k V b K) (w : ⋀[k]^2 V)
  exact h.trans (Koszul.MetabelianLieModel.generatorBracketMap_eq_zero_of_mem k V K w.property)

/-- The original second derived ideal is killed by actual functoriality of the derived series. -/
theorem secondDerivedIdeal_le_freeLieToKoszulModel_ker :
    LieAlgebra.derivedSeries k (FreeLieAlgebra k ι) 2 ≤
      (freeLieToKoszulModel k V b K).ker := by
  apply LieIdeal.map_eq_bot_iff.mp
  apply le_bot_iff.mp
  have h := LieIdeal.derivedSeries_map_le (f := freeLieToKoszulModel k V b K) 2
  rw [Koszul.MetabelianLieModel.derived_two_eq_bot] at h
  exact h

theorem quadraticMetabelianRelationIdeal_le_freeLieToKoszulModel_ker :
    quadraticMetabelianRelationIdeal k V b K ≤ (freeLieToKoszulModel k V b K).ker :=
  sup_le (quadraticRelationIdeal_le_freeLieToKoszulModel_ker k V b K)
    (secondDerivedIdeal_le_freeLieToKoszulModel_ker k V b K)

/-- The actual vector-linear map descended through the proved kernel containment. -/
def quadraticMetabelianToKoszulModelLinear :
    QuadraticMetabelianFreeQuotient k V b K →ₗ[k] Koszul.MetabelianLieModel k V K :=
  (quadraticMetabelianRelationIdeal k V b K).toSubmodule.liftQ
    (freeLieToKoszulModel k V b K).toLinearMap
    (quadraticMetabelianRelationIdeal_le_freeLieToKoszulModel_ker k V b K)

@[simp]
theorem quadraticMetabelianToKoszulModelLinear_projection (x : FreeLieAlgebra k ι) :
    quadraticMetabelianToKoszulModelLinear k V b K (quadraticMetabelianProjection k V b K x) =
      freeLieToKoszulModel k V b K x :=
  Submodule.liftQ_apply _ _ _

/-- The descended actual map preserves actual Lie brackets. -/
def quadraticMetabelianToKoszulModel :
    QuadraticMetabelianFreeQuotient k V b K →ₗ⁅k⁆ Koszul.MetabelianLieModel k V K where
  __ := quadraticMetabelianToKoszulModelLinear k V b K
  map_lie' := by
    intro x y
    obtain ⟨x, rfl⟩ := quadraticMetabelianProjection_surjective k V b K x
    obtain ⟨y, rfl⟩ := quadraticMetabelianProjection_surjective k V b K y
    change quadraticMetabelianToKoszulModelLinear k V b K
      ⁅quadraticMetabelianProjection k V b K x, quadraticMetabelianProjection k V b K y⁆ =
      ⁅quadraticMetabelianToKoszulModelLinear k V b K (quadraticMetabelianProjection k V b K x),
        quadraticMetabelianToKoszulModelLinear k V b K (quadraticMetabelianProjection k V b K y)⁆
    rw [← LieHom.map_lie, quadraticMetabelianToKoszulModelLinear_projection,
      quadraticMetabelianToKoszulModelLinear_projection,
      quadraticMetabelianToKoszulModelLinear_projection]
    exact LieHom.map_lie _ _ _

theorem quadraticMetabelianToKoszulModel_generator (u : V) :
    quadraticMetabelianToKoszulModel k V b K (quadraticMetabelianGenerators k V b K u) =
      Koszul.MetabelianLieModel.generatorInclusion k V K u := by
  change quadraticMetabelianToKoszulModelLinear k V b K
    (quadraticMetabelianProjection k V b K (freeVectorGenerators k V b u)) = _
  rw [quadraticMetabelianToKoszulModelLinear_projection, freeLieToKoszulModel_generator]

end ChenRanks.LieComparison
