import ChenRanks.QuadraticMetabelianFreeLie

/-!
# The actual metabelian quotient of the actual quadratic holonomy algebra

The holonomy algebra here is the actual free Lie algebra on the original
basis, divided by the native Lie ideal generated by the original
quadratic subspace. Its metabelian quotient is then formed using its
own native second derived ideal. Actual quotient maps and derived-series
functoriality prove that this iterated quotient equals the already
constructed free quotient by the quadratic and free second-derived
ideals. No identification of derived ideals is assumed, and no group
or Malcev comparison is included in this purely Lie-algebra statement.
-/

noncomputable section

namespace ChenRanks.LieComparison

variable (k : Type*) [Field k]
variable (V : Type*) [AddCommGroup V] [Module k V]
variable {ι : Type*} (b : _root_.Module.Basis ι k V)
variable (K : Submodule k (⋀[k]^2 V))

/-- The actual original quadratic free-Lie quotient. -/
abbrev QuadraticHolonomyLie := FreeLieAlgebra k ι ⧸ quadraticRelationIdeal k V b K

/-- The genuine quotient Lie homomorphism before taking the metabelian quotient. -/
def quadraticHolonomyProjection : FreeLieAlgebra k ι →ₗ⁅k⁆ QuadraticHolonomyLie k V b K where
  __ := (quadraticRelationIdeal k V b K).toSubmodule.mkQ
  map_lie' := by intro x y; rfl

theorem quadraticHolonomyProjection_surjective :
    Function.Surjective (quadraticHolonomyProjection k V b K) :=
  Submodule.mkQ_surjective (quadraticRelationIdeal k V b K).toSubmodule

@[simp]
theorem quadraticHolonomyProjection_eq_zero_iff (x : FreeLieAlgebra k ι) :
    quadraticHolonomyProjection k V b K x = 0 ↔ x ∈ quadraticRelationIdeal k V b K :=
  Submodule.Quotient.mk_eq_zero _

/-- The native metabelian quotient of the native original quadratic algebra. -/
abbrev HolonomyMetabelianQuotient :=
  QuadraticHolonomyLie k V b K ⧸
    LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2

/-- The actual second quotient projection. -/
def holonomyMetabelianProjection :
    QuadraticHolonomyLie k V b K →ₗ⁅k⁆ HolonomyMetabelianQuotient k V b K where
  __ := (LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2).toSubmodule.mkQ
  map_lie' := by intro x y; rfl

theorem holonomyMetabelianProjection_surjective :
    Function.Surjective (holonomyMetabelianProjection k V b K) :=
  Submodule.mkQ_surjective
    (LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2).toSubmodule

@[simp]
theorem holonomyMetabelianProjection_eq_zero_iff (x : QuadraticHolonomyLie k V b K) :
    holonomyMetabelianProjection k V b K x = 0 ↔
      x ∈ LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2 :=
  Submodule.Quotient.mk_eq_zero _

theorem holonomyMetabelianProjection_ker :
    (holonomyMetabelianProjection k V b K).ker =
      LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2 := by
  ext x
  exact holonomyMetabelianProjection_eq_zero_iff k V b K x

/-- Metabelianity is proved for the actual iterated quotient. -/
theorem holonomyMetabelianQuotient_derived_two_eq_bot :
    LieAlgebra.derivedSeries k (HolonomyMetabelianQuotient k V b K) 2 = ⊥ := by
  rw [← LieIdeal.derivedSeries_map_eq
    (f := holonomyMetabelianProjection k V b K) 2
      (holonomyMetabelianProjection_surjective k V b K)]
  apply LieIdeal.map_eq_bot_iff.mpr
  rw [holonomyMetabelianProjection_ker]

/-- The actual composite from the original free Lie algebra. -/
def freeToHolonomyMetabelian :
    FreeLieAlgebra k ι →ₗ⁅k⁆ HolonomyMetabelianQuotient k V b K :=
  (holonomyMetabelianProjection k V b K).comp (quadraticHolonomyProjection k V b K)

theorem quadraticRelationIdeal_le_freeToHolonomyMetabelian_ker :
    quadraticRelationIdeal k V b K ≤ (freeToHolonomyMetabelian k V b K).ker := by
  intro x hx
  change holonomyMetabelianProjection k V b K (quadraticHolonomyProjection k V b K x) = 0
  rw [(quadraticHolonomyProjection_eq_zero_iff k V b K x).mpr hx, map_zero]

theorem secondDerivedIdeal_le_freeToHolonomyMetabelian_ker :
    LieAlgebra.derivedSeries k (FreeLieAlgebra k ι) 2 ≤
      (freeToHolonomyMetabelian k V b K).ker := by
  apply LieIdeal.map_eq_bot_iff.mp
  apply le_bot_iff.mp
  have h := LieIdeal.derivedSeries_map_le (f := freeToHolonomyMetabelian k V b K) 2
  rw [holonomyMetabelianQuotient_derived_two_eq_bot] at h
  exact h

theorem quadraticMetabelianRelationIdeal_le_freeToHolonomyMetabelian_ker :
    quadraticMetabelianRelationIdeal k V b K ≤ (freeToHolonomyMetabelian k V b K).ker :=
  sup_le (quadraticRelationIdeal_le_freeToHolonomyMetabelian_ker k V b K)
    (secondDerivedIdeal_le_freeToHolonomyMetabelian_ker k V b K)

/-- Actual descent of the original composite through the original summed ideal. -/
def quadraticMetabelianToHolonomyMetabelianLinear :
    QuadraticMetabelianFreeQuotient k V b K →ₗ[k] HolonomyMetabelianQuotient k V b K :=
  (quadraticMetabelianRelationIdeal k V b K).toSubmodule.liftQ
    (freeToHolonomyMetabelian k V b K).toLinearMap
    (quadraticMetabelianRelationIdeal_le_freeToHolonomyMetabelian_ker k V b K)

@[simp]
theorem quadraticMetabelianToHolonomyMetabelianLinear_projection (x : FreeLieAlgebra k ι) :
    quadraticMetabelianToHolonomyMetabelianLinear k V b K
      (quadraticMetabelianProjection k V b K x) = freeToHolonomyMetabelian k V b K x :=
  Submodule.liftQ_apply _ _ _

def quadraticMetabelianToHolonomyMetabelian :
    QuadraticMetabelianFreeQuotient k V b K →ₗ⁅k⁆ HolonomyMetabelianQuotient k V b K where
  __ := quadraticMetabelianToHolonomyMetabelianLinear k V b K
  map_lie' := by
    intro x y
    obtain ⟨x, rfl⟩ := quadraticMetabelianProjection_surjective k V b K x
    obtain ⟨y, rfl⟩ := quadraticMetabelianProjection_surjective k V b K y
    change quadraticMetabelianToHolonomyMetabelianLinear k V b K
      ⁅quadraticMetabelianProjection k V b K x, quadraticMetabelianProjection k V b K y⁆ =
      ⁅quadraticMetabelianToHolonomyMetabelianLinear k V b K (quadraticMetabelianProjection k V b K x),
        quadraticMetabelianToHolonomyMetabelianLinear k V b K (quadraticMetabelianProjection k V b K y)⁆
    rw [← LieHom.map_lie, quadraticMetabelianToHolonomyMetabelianLinear_projection,
      quadraticMetabelianToHolonomyMetabelianLinear_projection,
      quadraticMetabelianToHolonomyMetabelianLinear_projection]
    exact LieHom.map_lie _ _ _

/-- The actual original quadratic ideal is killed by the original summed-ideal projection. -/
theorem quadraticRelationIdeal_le_quadraticMetabelianProjection_ker :
    quadraticRelationIdeal k V b K ≤ (quadraticMetabelianProjection k V b K).ker := by
  rw [quadraticMetabelianProjection_ker]
  exact le_sup_left

def holonomyToQuadraticMetabelianLinear :
    QuadraticHolonomyLie k V b K →ₗ[k] QuadraticMetabelianFreeQuotient k V b K :=
  (quadraticRelationIdeal k V b K).toSubmodule.liftQ
    (quadraticMetabelianProjection k V b K).toLinearMap
    (quadraticRelationIdeal_le_quadraticMetabelianProjection_ker k V b K)

@[simp]
theorem holonomyToQuadraticMetabelianLinear_projection (x : FreeLieAlgebra k ι) :
    holonomyToQuadraticMetabelianLinear k V b K (quadraticHolonomyProjection k V b K x) =
      quadraticMetabelianProjection k V b K x := Submodule.liftQ_apply _ _ _

def holonomyToQuadraticMetabelian :
    QuadraticHolonomyLie k V b K →ₗ⁅k⁆ QuadraticMetabelianFreeQuotient k V b K where
  __ := holonomyToQuadraticMetabelianLinear k V b K
  map_lie' := by
    intro x y
    obtain ⟨x, rfl⟩ := quadraticHolonomyProjection_surjective k V b K x
    obtain ⟨y, rfl⟩ := quadraticHolonomyProjection_surjective k V b K y
    change holonomyToQuadraticMetabelianLinear k V b K
      ⁅quadraticHolonomyProjection k V b K x, quadraticHolonomyProjection k V b K y⁆ =
      ⁅holonomyToQuadraticMetabelianLinear k V b K (quadraticHolonomyProjection k V b K x),
        holonomyToQuadraticMetabelianLinear k V b K (quadraticHolonomyProjection k V b K y)⁆
    rw [← LieHom.map_lie, holonomyToQuadraticMetabelianLinear_projection,
      holonomyToQuadraticMetabelianLinear_projection,
      holonomyToQuadraticMetabelianLinear_projection]
    exact LieHom.map_lie _ _ _

/-- The second derived ideal of the actual quadratic algebra is killed by functoriality. -/
theorem holonomySecondDerived_le_holonomyToQuadraticMetabelian_ker :
    LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2 ≤
      (holonomyToQuadraticMetabelian k V b K).ker := by
  apply LieIdeal.map_eq_bot_iff.mp
  apply le_bot_iff.mp
  have h := LieIdeal.derivedSeries_map_le (f := holonomyToQuadraticMetabelian k V b K) 2
  rw [quadraticMetabelianFreeQuotient_derived_two_eq_bot] at h
  exact h

def holonomyMetabelianToQuadraticLinear :
    HolonomyMetabelianQuotient k V b K →ₗ[k] QuadraticMetabelianFreeQuotient k V b K :=
  (LieAlgebra.derivedSeries k (QuadraticHolonomyLie k V b K) 2).toSubmodule.liftQ
    (holonomyToQuadraticMetabelian k V b K).toLinearMap
    (holonomySecondDerived_le_holonomyToQuadraticMetabelian_ker k V b K)

@[simp]
theorem holonomyMetabelianToQuadraticLinear_projection (x : QuadraticHolonomyLie k V b K) :
    holonomyMetabelianToQuadraticLinear k V b K (holonomyMetabelianProjection k V b K x) =
      holonomyToQuadraticMetabelian k V b K x := Submodule.liftQ_apply _ _ _

def holonomyMetabelianToQuadratic :
    HolonomyMetabelianQuotient k V b K →ₗ⁅k⁆ QuadraticMetabelianFreeQuotient k V b K where
  __ := holonomyMetabelianToQuadraticLinear k V b K
  map_lie' := by
    intro x y
    obtain ⟨x, rfl⟩ := holonomyMetabelianProjection_surjective k V b K x
    obtain ⟨y, rfl⟩ := holonomyMetabelianProjection_surjective k V b K y
    change holonomyMetabelianToQuadraticLinear k V b K
      ⁅holonomyMetabelianProjection k V b K x, holonomyMetabelianProjection k V b K y⁆ =
      ⁅holonomyMetabelianToQuadraticLinear k V b K (holonomyMetabelianProjection k V b K x),
        holonomyMetabelianToQuadraticLinear k V b K (holonomyMetabelianProjection k V b K y)⁆
    rw [← LieHom.map_lie, holonomyMetabelianToQuadraticLinear_projection,
      holonomyMetabelianToQuadraticLinear_projection,
      holonomyMetabelianToQuadraticLinear_projection]
    exact LieHom.map_lie _ _ _

/-- The actual two quotient maps cancel on every original free-Lie class. -/
theorem holonomyMetabelianToQuadratic_quadraticMetabelianToHolonomyMetabelian
    (x : QuadraticMetabelianFreeQuotient k V b K) :
    holonomyMetabelianToQuadratic k V b K
      (quadraticMetabelianToHolonomyMetabelian k V b K x) = x := by
  obtain ⟨y, rfl⟩ := quadraticMetabelianProjection_surjective k V b K x
  change holonomyMetabelianToQuadraticLinear k V b K
    (quadraticMetabelianToHolonomyMetabelianLinear k V b K
      (quadraticMetabelianProjection k V b K y)) = _
  rw [quadraticMetabelianToHolonomyMetabelianLinear_projection]
  change holonomyMetabelianToQuadraticLinear k V b K
    (holonomyMetabelianProjection k V b K (quadraticHolonomyProjection k V b K y)) = _
  rw [holonomyMetabelianToQuadraticLinear_projection]
  exact holonomyToQuadraticMetabelianLinear_projection k V b K y

theorem quadraticMetabelianToHolonomyMetabelian_holonomyMetabelianToQuadratic
    (x : HolonomyMetabelianQuotient k V b K) :
    quadraticMetabelianToHolonomyMetabelian k V b K
      (holonomyMetabelianToQuadratic k V b K x) = x := by
  obtain ⟨y, rfl⟩ := holonomyMetabelianProjection_surjective k V b K x
  obtain ⟨z, rfl⟩ := quadraticHolonomyProjection_surjective k V b K y
  change quadraticMetabelianToHolonomyMetabelianLinear k V b K
    (holonomyMetabelianToQuadraticLinear k V b K
      (holonomyMetabelianProjection k V b K (quadraticHolonomyProjection k V b K z))) = _
  rw [holonomyMetabelianToQuadraticLinear_projection]
  change quadraticMetabelianToHolonomyMetabelianLinear k V b K
    (holonomyToQuadraticMetabelianLinear k V b K (quadraticHolonomyProjection k V b K z)) = _
  rw [holonomyToQuadraticMetabelianLinear_projection,
    quadraticMetabelianToHolonomyMetabelianLinear_projection]
  rfl

/-- A proved genuine Lie equivalence, using the original holonomy algebra's
own second derived ideal, rather than defining its quotient to equal the target. -/
def holonomyMetabelianQuadraticEquiv :
    HolonomyMetabelianQuotient k V b K ≃ₗ⁅k⁆ QuadraticMetabelianFreeQuotient k V b K :=
  LieEquiv.ofBijective (holonomyMetabelianToQuadratic k V b K)
    ⟨Function.LeftInverse.injective
      (quadraticMetabelianToHolonomyMetabelian_holonomyMetabelianToQuadratic k V b K),
      Function.RightInverse.surjective
        (holonomyMetabelianToQuadratic_quadraticMetabelianToHolonomyMetabelian k V b K)⟩

end ChenRanks.LieComparison
