import ChenRanks.ScalarGroupAssociatedGraded
import ChenRanks.GroupLowerCentralBracketGeneration
import Mathlib.Algebra.Lie.Free

/-!
# Actual degree-one generation after genuine scalar extension

The actual inverse image of a scalar Lie subalgebra is an actual rational
Lie subalgebra. Rational generation and true tensor-product induction
then prove scalar generation. A native free-Lie lift of an actual basis
of the actual scalarized first quotient is consequently surjective.
-/

noncomputable section

open TensorProduct
open scoped TensorProduct

namespace ChenRanks

variable (k : Type*) [Field k] [CharZero k]
variable (G : Type*) [Group G]

/-- The original one-tensor inclusion is the actual rational linear map. -/
def scalarGroupOneTensor :
    rationalGroupAssociatedGraded G →ₗ[ℚ] scalarGroupAssociatedGraded k G :=
  TensorProduct.mk ℚ k (rationalGroupAssociatedGraded G) 1

/-- The original one-tensor map retains the actual original Lie bracket. -/
theorem scalarGroupOneTensor_lie (x y : rationalGroupAssociatedGraded G) :
    scalarGroupOneTensor k G ⁅x, y⁆ =
      ⁅scalarGroupOneTensor k G x, scalarGroupOneTensor k G y⁆ := by
  change (1 : k) ⊗ₜ[ℚ] ⁅x, y⁆ = ⁅(1 : k) ⊗ₜ[ℚ] x, (1 : k) ⊗ₜ[ℚ] y⁆
  rw [LieAlgebra.ExtendScalars.bracket_tmul, one_mul]

/-- This actual cancellation identity matches every rational homogeneous
inclusion, including arbitrary rational first-quotient elements. -/
theorem scalarGroupGradedInclusion_baseChange (n : ℕ)
    (x : k ⊗[ℚ] rationalLowerCentralPiece G n) :
    scalarGroupGradedInclusion k G n (scalarGroupPieceBaseChangeEquiv k G n x) =
      AlgebraTensorModule.lTensor k k (rationalGroupGradedInclusion G n) x := by
  rw [scalarGroupGradedInclusion, LinearMap.comp_apply]
  change AlgebraTensorModule.lTensor k k (rationalGroupGradedInclusion G n)
    ((scalarGroupPieceBaseChangeEquiv k G n).symm
      (scalarGroupPieceBaseChangeEquiv k G n x)) = _
  rw [LinearEquiv.symm_apply_apply]

/-- The actual preimage uses the original rational group Lie algebra,
not a supplied Lie-generation witness. -/
def scalarGroupSubalgebraRationalPreimage
    (H : LieSubalgebra k (scalarGroupAssociatedGraded k G)) :
    LieSubalgebra ℚ (rationalGroupAssociatedGraded G) where
  __ := (H.toSubmodule.restrictScalars ℚ).comap (scalarGroupOneTensor k G)
  lie_mem' {x} {y} hx hy := by
    change scalarGroupOneTensor k G ⁅x, y⁆ ∈ H
    rw [scalarGroupOneTensor_lie]
    exact H.lie_mem hx hy

/-- The actual scalar Lie algebra is generated by its actual scalarized
original first lower-central quotient. No comparison or finite generation
is assumed. -/
theorem scalarGroupGradedLieSubalgebra_eq_top
    (H : LieSubalgebra k (scalarGroupAssociatedGraded k G))
    (hfirst : ∀ x : scalarLowerCentralPiece k G 0,
      scalarGroupGradedInclusion k G 0 x ∈ H) : H = ⊤ := by
  have hpre : scalarGroupSubalgebraRationalPreimage k G H = ⊤ := by
    apply rationalGroupGradedLieSubalgebra_eq_top G
    intro x
    change (1 : k) ⊗ₜ[ℚ] rationalGroupGradedInclusion G 0 x ∈ H
    have hx := hfirst (scalarGroupPieceBaseChangeEquiv k G 0 ((1 : k) ⊗ₜ[ℚ] x))
    rw [scalarGroupGradedInclusion_baseChange, AlgebraTensorModule.lTensor_tmul] at hx
    exact hx
  have hone (x : rationalGroupAssociatedGraded G) : (1 : k) ⊗ₜ[ℚ] x ∈ H := by
    have hx : x ∈ scalarGroupSubalgebraRationalPreimage k G H := by
      rw [hpre]
      exact Submodule.mem_top
    exact hx
  apply top_unique
  intro x _hx
  clear _hx
  induction x using TensorProduct.induction_on with
  | zero => exact H.zero_mem
  | add x y hx hy => exact H.add_mem hx hy
  | tmul c x =>
    have h := H.smul_mem c (hone x)
    simpa only [TensorProduct.smul_tmul', smul_eq_mul, mul_one] using h

theorem scalarGroupAssociatedGraded_lieSpan_first_eq_top :
    LieSubalgebra.lieSpan k (scalarGroupAssociatedGraded k G)
      (Set.range (scalarGroupGradedInclusion k G 0)) = ⊤ := by
  apply scalarGroupGradedLieSubalgebra_eq_top k G
  intro x
  exact LieSubalgebra.subset_lieSpan ⟨x, rfl⟩

variable {ι : Type*} [Fintype ι]
variable (b : _root_.Module.Basis ι k (scalarLowerCentralPiece k G 0))

omit [Fintype ι] in
/-- The actual free-Lie universal map from an actual first-quotient basis. -/
def scalarGroupAssociatedGradedFreeLift :
    FreeLieAlgebra k ι →ₗ⁅k⁆ scalarGroupAssociatedGraded k G :=
  FreeLieAlgebra.lift k (fun i => scalarGroupGradedInclusion k G 0 (b i))

omit [Fintype ι] in
@[simp] theorem scalarGroupAssociatedGradedFreeLift_generator (i : ι) :
    scalarGroupAssociatedGradedFreeLift k G b (FreeLieAlgebra.of k i) =
      scalarGroupGradedInclusion k G 0 (b i) :=
  FreeLieAlgebra.lift_of_apply _ i

/-- Actual finite-basis expansion places the whole original first
quotient in the actual native Lie range. -/
theorem scalarGroupAssociatedGradedFreeLift_first_mem_range
    (x : scalarLowerCentralPiece k G 0) :
    scalarGroupGradedInclusion k G 0 x ∈
      (scalarGroupAssociatedGradedFreeLift k G b).range := by
  have hdec := congrArg (scalarGroupGradedInclusion k G 0) (b.sum_repr x)
  simp only [map_sum, map_smul] at hdec
  rw [← hdec]
  apply Submodule.sum_mem (scalarGroupAssociatedGradedFreeLift k G b).range.toSubmodule
  intro i _hi
  apply Submodule.smul_mem
  exact ⟨FreeLieAlgebra.of k i, scalarGroupAssociatedGradedFreeLift_generator k G b i⟩

theorem scalarGroupAssociatedGradedFreeLift_range :
    (scalarGroupAssociatedGradedFreeLift k G b).range = ⊤ :=
  scalarGroupGradedLieSubalgebra_eq_top k G _
    (scalarGroupAssociatedGradedFreeLift_first_mem_range k G b)

theorem scalarGroupAssociatedGradedFreeLift_surjective :
    Function.Surjective (scalarGroupAssociatedGradedFreeLift k G b) :=
  (LieHom.range_eq_top (scalarGroupAssociatedGradedFreeLift k G b)).mp
    (scalarGroupAssociatedGradedFreeLift_range k G b)

end ChenRanks
