import ChenRanks.SymmetricDualPuncturedSupport
import ChenRanks.KoszulProjectiveQuotientMap

/-!
# Every actual relevant prime of the resonance Proj

The genuine symmetric-algebra irrelevant ideal is proved equal to the
actual ideal generated by all degree-one symmetric generators. The
positive-degree inclusion uses the already proved surjectivity of the
actual Koszul multiplication differential in every homogeneous degree;
its image lies in the true generator ideal by actual tensor induction.

Each actual native projective point therefore supplies an actual affine
prime in the actual punctured cone. Restricting the proved all-affine-prime
annihilator support cover gives a cover of every actual relevant prime,
and hence the actual quotient Proj point image. It does not rely on an
assumption that arbitrary projective points are vector-line points.

Only topological support is asserted. Primality and irreducibility of the
linear pieces, reducedness, and the canonical module decomposition remain
separate statements.
-/

noncomputable section

open scoped TensorProduct

namespace ChenRanks.Koszul

open ChenRanks.Resonance

universe u

variable (k E : Type u) [Field k] [AddCommGroup E] [_root_.Module k E]
variable {ι : Type u} [Fintype ι]
  (b : _root_.Module.Basis ι k (_root_.Module.Dual k E))

omit [Fintype ι] in
/-- The true multiplication differential lands in the true ideal of
degree-one generators, as proved on actual pure tensors and their sums. -/
theorem delta1_mem_symmetricDualOriginIdeal
    (z : C1 k (_root_.Module.Dual k E)) :
    delta1 k (_root_.Module.Dual k E) z ∈ symmetricDualOriginIdeal k E := by
  induction z using TensorProduct.induction_on with
  | zero => exact Ideal.zero_mem _
  | add x y hx hy =>
    rw [map_add]
    exact Ideal.add_mem _ hx hy
  | tmul s φ =>
    rw [delta1_tmul]
    exact Ideal.mul_mem_left _ s (Ideal.subset_span (Set.mem_range_self φ))

/-- The genuine native irrelevant ideal is precisely the true symmetric
generator ideal; no generation-in-degree-one hypothesis is input. -/
theorem homogeneousS_irrelevant_toIdeal_eq_origin :
    (HomogeneousIdeal.irrelevant (homogeneousS k (_root_.Module.Dual k E) b)).toIdeal =
      symmetricDualOriginIdeal k E := by
  apply le_antisymm
  · apply (HomogeneousIdeal.toIdeal_irrelevant_le _).mpr
    intro n hn s hs
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
    obtain ⟨z, hz⟩ := multiplicationAtDegree_surjective k (_root_.Module.Dual k E) b m
      (⟨s, hs⟩ : homogeneousS k (_root_.Module.Dual k E) b (m + 1))
    have hz' : delta1 k (_root_.Module.Dual k E) z.val = s := congrArg Subtype.val hz
    rw [← hz']
    exact delta1_mem_symmetricDualOriginIdeal k E z.val
  · apply Ideal.span_le.mpr
    rintro s ⟨φ, rfl⟩
    exact HomogeneousIdeal.mem_irrelevant_of_mem _ (by decide)
      (homogeneousS_ι k (_root_.Module.Dual k E) b φ)

omit [Fintype ι] in
/-- Forgetting the genuine native homogeneous structure gives the same
underlying actual prime of the same original symmetric algebra. -/
def symmetricDualProjectiveAffinePrime
    (p : ProjectiveSpectrum (homogeneousS k (_root_.Module.Dual k E) b)) :
    PrimeSpectrum (S k (_root_.Module.Dual k E)) :=
  ⟨p.asHomogeneousIdeal.toIdeal, p.isPrime⟩

/-- Every actual relevant homogeneous prime is in the true punctured
affine cone, by the proved exact irrelevant/generator ideal equality. -/
theorem symmetricDualProjectiveAffinePrime_mem_punctured
    (p : ProjectiveSpectrum (homogeneousS k (_root_.Module.Dual k E) b)) :
    symmetricDualProjectiveAffinePrime k E b p ∈ symmetricDualPuncturedOpen k E := by
  change ¬ symmetricDualOriginIdeal k E ≤ p.asHomogeneousIdeal.toIdeal
  rw [← homogeneousS_irrelevant_toIdeal_eq_origin k E b]
  exact p.not_irrelevant_le

section AlgebraicallyClosed

variable [FiniteDimensional k E] [IsAlgClosed k] [CharZero k]

/-- The actual original annihilator's native projective zero locus is
the union of the actual original maximal-isotropic linear cones, at all
actual relevant homogeneous primes, rather than only vector-line points. -/
theorem symmetricDual_projective_annihilator_zeroLocus_eq
    (I : Submodule k (⋀[k]^2 E))
    (hsep : ∀ P : Submodule k E,
      IsMaximalIsotropic (relationWedge (cupQuotient I)) P →
      2 ≤ _root_.Module.finrank k P → mixedExterior P ⊓ I = pureExterior P) :
    ProjectiveSpectrum.zeroLocus (homogeneousS k (_root_.Module.Dual k E) b)
        (symmetricDualActualAnnihilator k E I : Set (S k (_root_.Module.Dual k E))) =
      ⋃ P : OriginalMaximalIsotropicFamily (cupQuotient I),
        ProjectiveSpectrum.zeroLocus (homogeneousS k (_root_.Module.Dual k E) b)
          (symmetricDualLinearIdeal k E P.val : Set (S k (_root_.Module.Dual k E))) := by
  ext p
  have hp := symmetricDualProjectiveAffinePrime_mem_punctured k E b p
  have hcover := Set.ext_iff.mp
    (symmetricDual_punctured_annihilator_zeroLocus_eq k E I hsep)
      (symmetricDualProjectiveAffinePrime k E b p)
  constructor
  · intro hAnn
    have hAnnAffine : symmetricDualProjectiveAffinePrime k E b p ∈
        PrimeSpectrum.zeroLocus (symmetricDualActualAnnihilator k E I :
          Set (S k (_root_.Module.Dual k E))) := hAnn
    obtain ⟨P, hP⟩ := Set.mem_iUnion.mp (hcover.mp ⟨hp, hAnnAffine⟩).2
    exact Set.mem_iUnion.mpr ⟨P, hP⟩
  · intro hCone
    obtain ⟨P, hP⟩ := Set.mem_iUnion.mp hCone
    have hConeAffine : symmetricDualProjectiveAffinePrime k E b p ∈
        symmetricDualLinearCone k E P.val := hP
    exact (hcover.mpr ⟨hp, Set.mem_iUnion.mpr ⟨P, hConeAffine⟩⟩).2

/-- The actual quotient Proj point image is the same actual finite
linear-cone union, using the native quotient map's proved range theorem. -/
theorem actualProjectiveResonancePointImage_eq_linearCones
    (I : Submodule k (⋀[k]^2 E))
    (hsep : ∀ P : Submodule k E,
      IsMaximalIsotropic (relationWedge (cupQuotient I)) P →
      2 ≤ _root_.Module.finrank k P → mixedExterior P ⊓ I = pureExterior P) :
    Set.range (quotientProjectivePointMap k (_root_.Module.Dual k E) b
      (actualHomogeneousAnnihilator k (_root_.Module.Dual k E) b
        (exteriorAnnihilator k E 2 I))) =
      ⋃ P : OriginalMaximalIsotropicFamily (cupQuotient I),
        ProjectiveSpectrum.zeroLocus (homogeneousS k (_root_.Module.Dual k E) b)
          (symmetricDualLinearIdeal k E P.val : Set (S k (_root_.Module.Dual k E))) := by
  rw [quotientProjectivePointMap_range]
  exact symmetricDual_projective_annihilator_zeroLocus_eq k E b I hsep

end AlgebraicallyClosed

end ChenRanks.Koszul
