import ChenRanks.SymmetricDualPuncturedSupport
import ChenRanks.KoszulGradedFunctoriality
import ChenRanks.KoszulHomogeneousAnnihilator
import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# Genuine symmetric quotient kernels and actual linear cone primes

For an actual surjective linear map `f`, the actual kernel of `Sym(f)`
is proved to be the ideal generated by the actual symmetric images of
`ker f`. The proof constructs a true linear right inverse. In the true
quotient by the generator ideal, its symmetric lift recovers the actual
quotient map on every original generator; this gives the opposite kernel
inclusion. The desired kernel equality is not an input.

Applied to the genuine restriction `Dual E → Dual P`, this identifies
the previously defined original linear cone ideal with the actual kernel
of its canonical symmetric restriction map. The target symmetric algebra
is a genuine domain over the field, so the actual cone ideal is prime.
Its generators have true degree one, so its homogeneity is also proved.
None of these facts is supplied as a hypothesis.
-/

noncomputable section

namespace ChenRanks.Koszul

section ActualSymmetricKernel

variable (k V W : Type*) [Field k] [AddCommGroup V] [AddCommGroup W]
  [_root_.Module k V] [_root_.Module k W]

/-- The actual kernel of a surjective symmetric-algebra map is generated
by the actual symmetric images of the original linear kernel. -/
theorem symmetricMap_kernel_eq_span_linearKernel
    (f : V →ₗ[k] W) (hf : Function.Surjective f) :
    RingHom.ker (symmetricMap k V W f).toRingHom =
      Ideal.span (Set.range (fun v : LinearMap.ker f ↦ SymmetricAlgebra.ι k V v.val)) := by
  let J := Ideal.span (Set.range (fun v : LinearMap.ker f ↦ SymmetricAlgebra.ι k V v.val))
  obtain ⟨g, hg⟩ := f.exists_rightInverse_of_surjective (LinearMap.range_eq_top.mpr hf)
  have hfg (w : W) : f (g w) = w := LinearMap.congr_fun hg w
  let q : S k V →ₐ[k] (S k V ⧸ J) := Ideal.Quotient.mkₐ k J
  let t : S k W →ₐ[k] (S k V ⧸ J) :=
    SymmetricAlgebra.lift ((q.toLinearMap.comp (SymmetricAlgebra.ι k V)).comp g)
  have hrecover : t.comp (symmetricMap k V W f) = q := by
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro v
    change SymmetricAlgebra.lift ((q.toLinearMap.comp (SymmetricAlgebra.ι k V)).comp g)
      (symmetricMap k V W f (SymmetricAlgebra.ι k V v)) = q (SymmetricAlgebra.ι k V v)
    rw [symmetricMap_ι, SymmetricAlgebra.lift_ι_apply]
    change Ideal.Quotient.mk J (SymmetricAlgebra.ι k V (g (f v))) =
      Ideal.Quotient.mk J (SymmetricAlgebra.ι k V v)
    apply Ideal.Quotient.eq.mpr
    rw [← map_sub]
    have hker : g (f v) - v ∈ LinearMap.ker f := by
      rw [LinearMap.mem_ker, map_sub, hfg, sub_self]
    exact Ideal.subset_span (Set.mem_range_self (⟨g (f v) - v, hker⟩ : LinearMap.ker f))
  apply le_antisymm
  · intro p hp
    have hp' : symmetricMap k V W f p = 0 := hp
    have hq : Ideal.Quotient.mk J p = 0 := by
      change q p = 0
      rw [← AlgHom.congr_fun hrecover p]
      change t (symmetricMap k V W f p) = 0
      rw [hp', map_zero]
    exact Ideal.Quotient.eq_zero_iff_mem.mp hq
  · apply Ideal.span_le.mpr
    rintro p ⟨v, rfl⟩
    change symmetricMap k V W f (SymmetricAlgebra.ι k V v.val) = 0
    rw [symmetricMap_ι, LinearMap.mem_ker.mp v.property, map_zero]

end ActualSymmetricKernel

universe u

variable (k E : Type u) [Field k] [AddCommGroup E] [_root_.Module k E]

/-- The original linear cone ideal is the actual kernel of the genuine
canonical symmetric restriction map to the original subspace dual. -/
theorem symmetricDualLinearIdeal_eq_restriction_kernel (P : Submodule k E) :
    symmetricDualLinearIdeal k E P =
      RingHom.ker (symmetricMap k (_root_.Module.Dual k E) (_root_.Module.Dual k P)
        (componentDualQuotient k E P)).toRingHom := by
  rw [symmetricMap_kernel_eq_span_linearKernel k (_root_.Module.Dual k E)
    (_root_.Module.Dual k P) (componentDualQuotient k E P)
      (componentDualQuotient_surjective k E P)]
  rfl

/-- Every original linear cone ideal is truly prime, including the
zero-subspace degeneration, because its genuine target is a domain. -/
theorem symmetricDualLinearIdeal_isPrime (P : Submodule k E) :
    (symmetricDualLinearIdeal k E P).IsPrime := by
  classical
  let c := _root_.Module.Basis.ofVectorSpace k (_root_.Module.Dual k P)
  let e := SymmetricAlgebra.equivMvPolynomial c
  letI : IsDomain (S k (_root_.Module.Dual k P)) :=
    Function.Injective.isDomain e.toRingHom e.injective
  rw [symmetricDualLinearIdeal_eq_restriction_kernel]
  exact RingHom.ker_isPrime _

variable {ι : Type u} [Fintype ι]
  (b : _root_.Module.Basis ι k (_root_.Module.Dual k E))

/-- The actual original linear ideal is homogeneous because every one
of its actual original generators has actual degree one. -/
theorem symmetricDualLinearIdeal_isHomogeneous (P : Submodule k E) :
    (symmetricDualLinearIdeal k E P).IsHomogeneous
      (homogeneousS k (_root_.Module.Dual k E) b) := by
  apply Ideal.homogeneous_span
  rintro s ⟨φ, rfl⟩
  exact ⟨1, homogeneousS_ι k (_root_.Module.Dual k E) b φ.val⟩

/-- The native homogeneous ideal has exactly the previously defined
actual original linear cone ideal as its underlying ideal. -/
def symmetricDualLinearHomogeneousIdeal (P : Submodule k E) :
    HomogeneousIdeal (homogeneousS k (_root_.Module.Dual k E) b) :=
  ⟨symmetricDualLinearIdeal k E P, symmetricDualLinearIdeal_isHomogeneous k E b P⟩

@[simp] theorem symmetricDualLinearHomogeneousIdeal_toIdeal (P : Submodule k E) :
    (symmetricDualLinearHomogeneousIdeal k E b P).toIdeal =
      symmetricDualLinearIdeal k E P := rfl

end ChenRanks.Koszul
