import ChenRanks.KoszulResonanceSupport
import Mathlib.AlgebraicGeometry.AlgClosed.Basic
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import Mathlib.RingTheory.FiniteType

/-!
# Actual closed points of the symmetric algebra on the original dual

The ring throughout is the genuine symmetric algebra on `Dual k E`.
Its actual canonical base-field morphism is locally of finite type, using
the finite basis polynomial equivalence. The actual closed-point theorem
then gives a scalar-compatible algebra homomorphism to `k`. Restricting
that homomorphism to the actual symmetric generators and applying the
canonical double-dual equivalence reconstructs an original vector `e`.
The same original prime is proved equal to its actual evaluation prime.

The punctured cone is defined by the true ideal generated by the actual
degree-one generators. A reconstructed point is in it precisely when
the reconstructed original vector is nonzero. No closed-point detector,
support cover, projective-point classification, or reducedness is input.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory

namespace ChenRanks.Koszul

universe u

variable (k E : Type u) [Field k] [AddCommGroup E] [_root_.Module k E]
  [FiniteDimensional k E]

/-- The genuine finite-type structure of the original symmetric algebra
on the original finite-dimensional dual. -/
theorem symmetricDual_finiteType :
    Algebra.FiniteType k (S k (_root_.Module.Dual k E)) := by
  let b := _root_.Module.finBasis k (_root_.Module.Dual k E)
  let e := SymmetricAlgebra.equivMvPolynomial b
  exact Algebra.FiniteType.of_surjective e.symm.toAlgHom e.symm.surjective

/-- The actual canonical scalar morphism of the original symmetric cone. -/
def symmetricDualScalarMorphism :
    Spec (CommRingCat.of (S k (_root_.Module.Dual k E))) ⟶ Spec (CommRingCat.of k) :=
  Spec.map (CommRingCat.ofHom (algebraMap k (S k (_root_.Module.Dual k E))))

/-- The actual scalar morphism is locally of finite type. -/
instance symmetricDualScalarMorphism_locallyOfFiniteType :
    LocallyOfFiniteType (symmetricDualScalarMorphism k E) := by
  letI := symmetricDual_finiteType k E
  dsimp only [symmetricDualScalarMorphism]
  rw [HasRingHomProperty.Spec_iff (P := @LocallyOfFiniteType)]
  exact RingHom.finiteType_algebraMap.mpr inferInstance

omit [FiniteDimensional k E] in
/-- The true ideal of the origin, generated by every actual degree-one
symmetric generator. -/
def symmetricDualOriginIdeal : Ideal (S k (_root_.Module.Dual k E)) :=
  Ideal.span (Set.range (SymmetricAlgebra.ι k (_root_.Module.Dual k E)))

omit [FiniteDimensional k E] in
/-- The actual punctured symmetric cone, as a native spectrum open. -/
def symmetricDualPuncturedOpen :
    TopologicalSpace.Opens (PrimeSpectrum (S k (_root_.Module.Dual k E))) :=
  ⟨(PrimeSpectrum.zeroLocus (symmetricDualOriginIdeal k E :
      Set (S k (_root_.Module.Dual k E)))).compl,
    (PrimeSpectrum.isClosed_zeroLocus _).isOpen_compl⟩

/-- A true vector evaluation point is in the actual punctured cone exactly
when its original vector is nonzero. This uses actual dual separation. -/
theorem vectorEvaluationPrime_mem_punctured_iff (e : E) :
    vectorEvaluationPrime k E e ∈ symmetricDualPuncturedOpen k E ↔ e ≠ 0 := by
  change ¬ symmetricDualOriginIdeal k E ≤
      pointEvaluationKernel k (_root_.Module.Dual k E) (pointOfVector k E e) ↔ e ≠ 0
  constructor
  · intro h he
    apply h
    apply Ideal.span_le.mpr
    rintro s ⟨φ, rfl⟩
    change pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) = 0
    simp only [pointEvaluation, SymmetricAlgebra.lift_ι_apply, pointOfVector,
      he, map_zero, LinearMap.zero_apply]
  · intro he h
    apply pointOfVector_ne_zero k E he
    apply LinearMap.ext
    intro φ
    have hφ := h (Ideal.subset_span (Set.mem_range_self φ))
    change pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) = 0 at hφ
    simpa only [pointEvaluation, SymmetricAlgebra.lift_ι_apply,
      LinearMap.zero_apply] using hφ

section AlgebraicallyClosed

variable [IsAlgClosed k]

/-- Every native closed point of the actual symmetric cone is the true
evaluation prime of an original vector, recovered by the genuine double
dual equivalence from its actual base-field point. -/
theorem symmetricDual_closedPoint_exists_vector
    (q : Spec (CommRingCat.of (S k (_root_.Module.Dual k E))))
    (hq : IsClosed ({q} : Set (Spec (CommRingCat.of (S k (_root_.Module.Dual k E)))))) :
    ∃ e : E, vectorEvaluationPrime k E e = q := by
  let R := S k (_root_.Module.Dual k E)
  let σX := symmetricDualScalarMorphism k E
  let p : Spec (CommRingCat.of k) ⟶ Spec (CommRingCat.of R) :=
    pointOfClosedPoint σX q hq
  have hscalar : CommRingCat.ofHom (algebraMap k R) ≫ Spec.preimage p =
      𝟙 (CommRingCat.of k) := by
    apply Spec.map_injective
    rw [Spec.map_comp, Spec.map_preimage, Spec.map_id]
    exact pointOfClosedPoint_comp σX q hq
  let a : R →ₐ[k] k :=
    { toRingHom := (Spec.preimage p).hom
      commutes' := by
        intro c
        exact congrArg (fun f : CommRingCat.of k ⟶ CommRingCat.of k ↦ f c) hscalar }
  let v : _root_.Module.Dual k (_root_.Module.Dual k E) :=
    a.toLinearMap.comp (SymmetricAlgebra.ι k (_root_.Module.Dual k E))
  let e : E := (_root_.Module.evalEquiv k E).symm v
  have hvector : pointOfVector k E e = v := by
    change _root_.Module.evalEquiv k E e = v
    exact (_root_.Module.evalEquiv k E).apply_symm_apply v
  have heval : pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e) = a := by
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro φ
    change SymmetricAlgebra.lift (pointOfVector k E e)
      (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ) =
        a (SymmetricAlgebra.ι k (_root_.Module.Dual k E) φ)
    rw [SymmetricAlgebra.lift_ι_apply]
    exact congrArg (fun f : _root_.Module.Dual k (_root_.Module.Dual k E) ↦ f φ) hvector
  refine ⟨e, ?_⟩
  calc
    vectorEvaluationPrime k E e =
        (Spec.map (Spec.preimage p)) (⟨⊥, inferInstance⟩ : PrimeSpectrum k) := by
      apply PrimeSpectrum.ext
      change RingHom.ker
          (pointEvaluation k (_root_.Module.Dual k E) (pointOfVector k E e)).toRingHom =
        Ideal.comap (Spec.preimage p).hom ⊥
      rw [heval, RingHom.ker_eq_comap_bot]
    _ = q := by
      rw [Spec.map_preimage]
      exact pointOfClosedPoint_apply σX q hq _

/-- Every actual closed point in the punctured symmetric cone has a true
nonzero original-vector witness, without a projective parametrization premise. -/
theorem symmetricDual_closedPuncturedPoint_exists_nonzero_vector
    (q : Spec (CommRingCat.of (S k (_root_.Module.Dual k E))))
    (hq : IsClosed ({q} : Set (Spec (CommRingCat.of (S k (_root_.Module.Dual k E))))))
    (hqpunctured : q ∈ symmetricDualPuncturedOpen k E) :
    ∃ e : E, e ≠ 0 ∧ vectorEvaluationPrime k E e = q := by
  obtain ⟨e, heq⟩ := symmetricDual_closedPoint_exists_vector k E q hq
  refine ⟨e, (vectorEvaluationPrime_mem_punctured_iff k E e).mp ?_, heq⟩
  rw [heq]
  exact hqpunctured

end AlgebraicallyClosed

end ChenRanks.Koszul
