import Mathlib
import ChenRanks.RelativeDVR

/-!
# The actual DVR at a transcendental rational function

The base DVR is the localization of `L[X]` at `(X)`, realized inside
`RatFunc L`.  For an actual element `r : F` transcendental over `L`, the
canonical isomorphism `RatFunc L ≃ₐ[L] L(r)` gives an actual embedding into
`F`.  The uniformizer maps to `r`.

No base-DVR or injectivity hypothesis is assumed.  This file does not yet
derive the finiteness of `F/L(r)` from the arrangement function-field data,
and it does not construct logarithmic residues or arrangement separation.
-/

namespace ChenRanks

open Polynomial IsLocalRing

noncomputable section

variable (L : Type*) [Field L]

/-- The actual prime ideal `(X)` of the polynomial ring. -/
def polynomialZeroIdeal : Ideal L[X] := Ideal.span {X}

instance polynomialZeroIdeal_isPrime : (polynomialZeroIdeal L).IsPrime := by
  change (Ideal.span {(X : L[X])}).IsPrime
  exact (Ideal.span_singleton_prime Polynomial.X_ne_zero).mpr Polynomial.prime_X

theorem polynomialZeroIdeal_ne_bot : polynomialZeroIdeal L ≠ ⊥ := by
  change Ideal.span {(X : L[X])} ≠ ⊥
  intro h
  have hX : (X : L[X]) ∈ Ideal.span {X} := Ideal.subset_span (by simp)
  have hzero : (X : L[X]) = 0 := Ideal.mem_bot.mp (h ▸ hX)
  exact Polynomial.X_ne_zero hzero

/-- The actual localization `L[X]_(X)`, represented inside `RatFunc L`. -/
def rationalFunctionZeroDVR : Subalgebra L[X] (RatFunc L) :=
  Localization.subalgebra (RatFunc L) (polynomialZeroIdeal L).primeCompl
    (polynomialZeroIdeal L).primeCompl_le_nonZeroDivisors

instance rationalFunctionZeroDVR_isLocalization :
    IsLocalization.AtPrime (rationalFunctionZeroDVR L) (polynomialZeroIdeal L) := by
  exact Localization.subalgebra.isLocalization_subalgebra (RatFunc L)
    (polynomialZeroIdeal L).primeCompl
    (polynomialZeroIdeal L).primeCompl_le_nonZeroDivisors

instance rationalFunctionZeroDVR_isFractionRing :
    IsFractionRing (rationalFunctionZeroDVR L) (RatFunc L) := by
  exact Localization.subalgebra.isFractionRing (RatFunc L)
    (polynomialZeroIdeal L).primeCompl
    (polynomialZeroIdeal L).primeCompl_le_nonZeroDivisors

instance rationalFunctionZeroDVR_isDiscreteValuationRing :
    IsDiscreteValuationRing (rationalFunctionZeroDVR L) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain L[X]
    (polynomialZeroIdeal_ne_bot L) (rationalFunctionZeroDVR L)

/-- The actual image of `X` in the local ring. -/
def rationalFunctionZeroUniformizer : rationalFunctionZeroDVR L :=
  algebraMap L[X] (rationalFunctionZeroDVR L) X

theorem rationalFunctionZeroUniformizer_ne_zero :
    rationalFunctionZeroUniformizer L ≠ 0 := by
  intro h
  apply Polynomial.X_ne_zero (R := L)
  exact (IsLocalization.injective (rationalFunctionZeroDVR L)
    (polynomialZeroIdeal L).primeCompl_le_nonZeroDivisors) (by
      simpa only [rationalFunctionZeroUniformizer, map_zero] using h)

theorem rationalFunctionZeroDVR_maximalIdeal :
    maximalIdeal (rationalFunctionZeroDVR L) =
      Ideal.span {rationalFunctionZeroUniformizer L} := by
  calc
    maximalIdeal (rationalFunctionZeroDVR L) =
        (polynomialZeroIdeal L).map (algebraMap L[X] (rationalFunctionZeroDVR L)) :=
      (IsLocalization.AtPrime.map_eq_maximalIdeal (polynomialZeroIdeal L)
        (rationalFunctionZeroDVR L)).symm
    _ = Ideal.span {rationalFunctionZeroUniformizer L} := by
      simp only [polynomialZeroIdeal, Ideal.map_span, Set.image_singleton,
        rationalFunctionZeroUniformizer]

theorem rationalFunctionZeroUniformizer_irreducible :
    Irreducible (rationalFunctionZeroUniformizer L) :=
  (IsDiscreteValuationRing.irreducible_iff_uniformizer
    (rationalFunctionZeroUniformizer L)).mpr (rationalFunctionZeroDVR_maximalIdeal L)

theorem rationalFunctionZeroUniformizer_mem_maximalIdeal :
    rationalFunctionZeroUniformizer L ∈ maximalIdeal (rationalFunctionZeroDVR L) := by
  rw [rationalFunctionZeroDVR_maximalIdeal]
  exact Ideal.subset_span (by simp)

section Embed

variable {L} {F : Type*} [Field F] [Algebra L F]

/-- The actual rational-function embedding obtained from a transcendental
element, with image the field generated by that element. -/
def transcendentalRatFuncMap (r : F) (hr : Transcendental L r) : RatFunc L →ₐ[L] F :=
  (IntermediateField.adjoin L {r}).val.comp
    (RatFunc.algEquivOfTranscendental r hr).toAlgHom

theorem transcendentalRatFuncMap_X (r : F) (hr : Transcendental L r) :
    transcendentalRatFuncMap r hr (RatFunc.X : RatFunc L) = r := by
  change (RatFunc.algEquivOfTranscendental r hr (RatFunc.X : RatFunc L) : F) = r
  exact RatFunc.algEquivOfTranscendental_X r hr

/-- The actual local-ring embedding, not an assumed injective map. -/
def transcendentalDVRMap (r : F) (hr : Transcendental L r) :
    rationalFunctionZeroDVR L →ₐ[L] F :=
  (transcendentalRatFuncMap r hr).comp
    ((rationalFunctionZeroDVR L).val.restrictScalars L)

theorem transcendentalDVRMap_injective (r : F) (hr : Transcendental L r) :
    Function.Injective (transcendentalDVRMap r hr) := by
  intro x y h
  apply Subtype.ext
  apply (transcendentalRatFuncMap r hr).injective
  exact h

theorem transcendentalDVRMap_uniformizer (r : F) (hr : Transcendental L r) :
    transcendentalDVRMap r hr (rationalFunctionZeroUniformizer L) = r := by
  change transcendentalRatFuncMap r hr
    (algebraMap L[X] (RatFunc L) X) = r
  rw [RatFunc.algebraMap_X]
  exact transcendentalRatFuncMap_X r hr

theorem transcendental_ne_zero_from_actual_DVR (r : F) (hr : Transcendental L r) :
    r ≠ 0 := by
  intro hrzero
  apply rationalFunctionZeroUniformizer_ne_zero L
  apply transcendentalDVRMap_injective r hr
  calc
    transcendentalDVRMap r hr (rationalFunctionZeroUniformizer L) = r :=
      transcendentalDVRMap_uniformizer r hr
    _ = 0 := hrzero
    _ = transcendentalDVRMap r hr 0 := (map_zero (transcendentalDVRMap r hr)).symm

/-- Combining the actual base DVR with the actual extension construction
produces a discrete valuation detecting a given transcendental element.

The remaining input is exposed: the extension field must be finite over
the explicit rational-function field embedding determined by `r`.  This
finiteness is not derived here from a relative transcendence-degree or
arrangement hypothesis.  Characteristic zero supplies separability.
The constructed valuation is trivial on all nonzero base-field elements,
expressed as valuation one on every base-field unit. -/
theorem exists_discrete_valuation_of_transcendental_finite
    [CharZero L] (r : F) (hr : Transcendental L r)
    (hfinite :
      letI : Algebra (RatFunc L) F := (transcendentalRatFuncMap r hr).toRingHom.toAlgebra
      FiniteDimensional (RatFunc L) F) :
    ∃ v : Valuation F (WithZero (Multiplicative ℤ)),
      v r < 1 ∧ v r ≠ 0 ∧
        ∀ u : Lˣ, v (algebraMap L F (u : L)) = 1 := by
  let algKF : Algebra (RatFunc L) F :=
    (transcendentalRatFuncMap r hr).toRingHom.toAlgebra
  letI : Algebra (RatFunc L) F := algKF
  letI : SMul (RatFunc L) F := algKF.toSMul
  letI : SMul (RatFunc L) (RatFunc L) := ⟨fun x y ↦ x * y⟩
  letI : FiniteDimensional (RatFunc L) F := hfinite
  let algAK : Algebra (rationalFunctionZeroDVR L) (RatFunc L) :=
    (rationalFunctionZeroDVR L).val.toRingHom.toAlgebra
  letI : Algebra (rationalFunctionZeroDVR L) (RatFunc L) := algAK
  letI : SMul (rationalFunctionZeroDVR L) (RatFunc L) := algAK.toSMul
  letI : IsFractionRing (rationalFunctionZeroDVR L) (RatFunc L) :=
    rationalFunctionZeroDVR_isFractionRing L
  let algAF : Algebra (rationalFunctionZeroDVR L) F :=
    (transcendentalDVRMap r hr).toRingHom.toAlgebra
  letI : Algebra (rationalFunctionZeroDVR L) F := algAF
  letI : SMul (rationalFunctionZeroDVR L) F := algAF.toSMul
  letI : IsScalarTower (rationalFunctionZeroDVR L) (RatFunc L) F :=
    IsScalarTower.of_algebraMap_eq (R := rationalFunctionZeroDVR L)
      (S := RatFunc L) (A := F) fun _ ↦ rfl
  obtain ⟨v, hlt, hne, _, hunit⟩ :=
    exists_discrete_field_valuation_above_nonzero (rationalFunctionZeroDVR L)
      (RatFunc L) F (rationalFunctionZeroUniformizer L)
      (rationalFunctionZeroUniformizer_mem_maximalIdeal L)
      (rationalFunctionZeroUniformizer_ne_zero L)
  have himage : algebraMap (rationalFunctionZeroDVR L) F
      (rationalFunctionZeroUniformizer L) = r := transcendentalDVRMap_uniformizer r hr
  refine ⟨v, ?_, ?_, ?_⟩
  · exact himage ▸ hlt
  · exact himage ▸ hne
  · intro u
    have hu := hunit (Units.map (algebraMap L (rationalFunctionZeroDVR L)) u)
    change v (transcendentalDVRMap r hr
      (algebraMap L (rationalFunctionZeroDVR L) (u : L))) = 1 at hu
    rw [(transcendentalDVRMap r hr).commutes] at hu
    exact hu

end Embed

end

end ChenRanks
